#include "Objects.h"
#include "Unimplemented.h"

extern "C" {
Ref FAddDelayedCall(RefArg rcvr);
Ref FAddDelayedSend(RefArg rcvr);
Ref FAddKeyCommand(RefArg rcvr);
Ref FAddKeyCommands(RefArg rcvr);
Ref FAddStepView(RefArg rcvr);
Ref FAddUndoAction(RefArg rcvr);
Ref FAddUndoCall(RefArg rcvr);
Ref FAddUndoSend(RefArg rcvr);
Ref FAddView(RefArg rcvr);
Ref FArrayToPoints(RefArg rcvr);
Ref FBlockKeyCommand(RefArg rcvr);
Ref FBookAvailable(RefArg rcvr);
Ref FBookRemoved(RefArg rcvr);
Ref FBuildContext(RefArg rcvr);
Ref FBusyBoxControl(RefArg rcvr);
Ref FCalibrateTablet(RefArg rcvr);
Ref FCaretRelativeToVisibleRect(RefArg rcvr);
Ref FCategorizeKeyCommands(RefArg rcvr);
Ref FChangeStylesOfRange(RefArg rcvr);
Ref FChildViewFramesX(RefArg rcvr);
Ref FClearHardKeymap(RefArg rcvr);
Ref FClearPopup(RefArg rcvr);
Ref FClearUndoStacks(RefArg rcvr);
Ref FClipboardCommand(RefArg rcvr);
Ref FCloseX(RefArg rcvr);
Ref FCommandKeyboardConnected(RefArg rcvr);
Ref FCountGesturePoints(RefArg rcvr);
Ref FCurrentExports(RefArg rcvr);
Ref FCurrentImports(RefArg rcvr);
Ref FDV(RefArg rcvr);
Ref FDebug(RefArg rcvr);
Ref FDebugMemoryStats(RefArg rcvr);
Ref FDebugRunUntilIdle(RefArg rcvr);
Ref FDeleteX(RefArg rcvr);
Ref FDirtyBoxX(RefArg rcvr);
Ref FDirtyX(RefArg rcvr);
Ref FDismissPopup(RefArg rcvr);
Ref FDisplaySplashGraphic(RefArg rcvr);
Ref FDoDrawing(RefArg rcvr);
Ref FDoPopup(RefArg rcvr);
Ref FDoScrubEffect(RefArg rcvr);
Ref FDragAndDrop(RefArg rcvr);
Ref FDragAndDropLtd(RefArg rcvr);
Ref FDragX(RefArg rcvr);
Ref FDrawPolygons(RefArg rcvr);
Ref FDrawShape(RefArg rcvr);
Ref FDropHilites(RefArg rcvr);
Ref FEffectX(RefArg rcvr);
Ref FEventPause(RefArg rcvr);
Ref FExitModalDialog(RefArg rcvr);
Ref FExtractData(RefArg rcvr);
Ref FExtractRangeAsRichString(RefArg rcvr);
Ref FExtractTextRange(RefArg rcvr);
Ref FFilterDialog(RefArg rcvr);
Ref FFindKeyCommand(RefArg rcvr);
Ref FFlushImports(RefArg rcvr);
Ref FForkScript(RefArg rcvr);
Ref FFulfillImportTable(RefArg rcvr);
Ref FGatherKeyCommands(RefArg rcvr);
Ref FGestalt(RefArg rcvr);
Ref FGesturePoint(RefArg rcvr);
Ref FGestureType(RefArg rcvr);
Ref FGetAlternates(RefArg rcvr);
Ref FGetCalibration(RefArg rcvr);
Ref FGetCaretBox(RefArg rcvr);
Ref FGetCaretInfo(RefArg rcvr);
Ref FGetClipboard(RefArg rcvr);
Ref FGetClipboardIcon(RefArg rcvr);
Ref FGetDrawBoxX(RefArg rcvr);
Ref FGetFlags(RefArg rcvr);
Ref FGetFrameStuff(RefArg rcvr);
Ref FGetHiliteOffsets(RefArg rcvr);
Ref FGetId(RefArg rcvr);
Ref FGetInkWordInfo(RefArg rcvr);
Ref FGetKeyView(RefArg rcvr);
Ref FGetPackages(RefArg rcvr);
Ref FGetPoint(RefArg rcvr);
Ref FGetPointsArray(RefArg rcvr);
Ref FGetPointsArrayXY(RefArg rcvr);
Ref FGetPolygons(RefArg rcvr);
Ref FGetPopup(RefArg rcvr);
Ref FGetRemoteWriting(RefArg rcvr);
Ref FGetRoot(RefArg rcvr);
Ref FGetScoreArray(RefArg rcvr);
Ref FGetStyleAtOffset(RefArg rcvr);
Ref FGetStylesOfRange(RefArg rcvr);
Ref FGetTextFlags(RefArg rcvr);
Ref FGetTrueModifiers(RefArg rcvr);
Ref FGetUndoState(RefArg rcvr);
Ref FGetUnitDownTime(RefArg rcvr);
Ref FGetUnitEndTime(RefArg rcvr);
Ref FGetUnitStartTime(RefArg rcvr);
Ref FGetUnitUpTime(RefArg rcvr);
Ref FGetView(RefArg rcvr);
Ref FGetWordArray(RefArg rcvr);
Ref FGlobalBoxX(RefArg rcvr);
Ref FGlobalOuterBoxX(RefArg rcvr);
Ref FHandleInkWord(RefArg rcvr);
Ref FHandleInsertItems(RefArg rcvr);
Ref FHandleKeyEvents(RefArg rcvr);
Ref FHandleRawInk(RefArg rcvr);
Ref FHandleUnit(RefArg rcvr);
Ref FHideCaret(RefArg rcvr);
Ref FHideX(RefArg rcvr);
Ref FHiliteOwner(RefArg rcvr);
Ref FHiliteUniqueX(RefArg rcvr);
Ref FHiliteViewChildren(RefArg rcvr);
Ref FHiliteX(RefArg rcvr);
Ref FHiliter(RefArg rcvr);
Ref FHobbleTablet(RefArg rcvr);
Ref FInRepeatedKeyCommand(RefArg rcvr);
Ref FInkOff(RefArg rcvr);
Ref FInkOffUnHobbled(RefArg rcvr);
Ref FInkOn(RefArg rcvr);
Ref FInsertItemsAtCaret(RefArg rcvr);
Ref FInsertTabletSample(RefArg rcvr);
Ref FInsetRect(RefArg rcvr);
Ref FInvertRect(RefArg rcvr);
Ref FIsCommandKeystroke(RefArg rcvr);
Ref FIsKeyDown(RefArg rcvr);
Ref FIsPrimShape(RefArg rcvr);
Ref FIsPtInRect(RefArg rcvr);
Ref FIsTabletCalibrationNeeded(RefArg rcvr);
Ref FJournalReplayALine(RefArg rcvr);
Ref FJournalReplayAStroke(RefArg rcvr);
Ref FJournalReplayBusy(RefArg rcvr);
Ref FJournalReplayStrokes(RefArg rcvr);
Ref FJournalStartRecord(RefArg rcvr);
Ref FJournalStopRecord(RefArg rcvr);
Ref FKeyIn(RefArg rcvr);
Ref FKeyboardConnected(RefArg rcvr);
Ref FLayoutTableX(RefArg rcvr);
Ref FLayoutVerticallyX(RefArg rcvr);
Ref FLoadFontCache(RefArg rcvr);
Ref FLocalBoxX(RefArg rcvr);
Ref FMakeBitmap(RefArg rcvr);
Ref FMakeLine(RefArg rcvr);
Ref FMakeRect(RefArg rcvr);
Ref FMakeShape(RefArg rcvr);
Ref FMakeText(RefArg rcvr);
Ref FMakeTextBox(RefArg rcvr);
Ref FMakeTextLines(RefArg rcvr);
Ref FMatchKeyMessage(RefArg rcvr);
Ref FModalDialog(RefArg rcvr);
Ref FModalRecognitionOff(RefArg rcvr);
Ref FModalRecognitionOn(RefArg rcvr);
Ref FModalState(RefArg rcvr);
Ref FMoveBehindX(RefArg rcvr);
Ref FNTKAlive(RefArg rcvr);
Ref FNTKDownload(RefArg rcvr);
Ref FNTKListener(RefArg rcvr);
Ref FNTKSend(RefArg rcvr);
Ref FNextKeyView(RefArg rcvr);
Ref FOffsetRect(RefArg rcvr);
Ref FOffsetShape(RefArg rcvr);
Ref FOffsetView(RefArg rcvr);
Ref FParentX(RefArg rcvr);
Ref FPenPos(RefArg rcvr);
Ref FPendingImports(RefArg rcvr);
Ref FPickViewKeyDown(RefArg rcvr);
Ref FPointToCharOffset(RefArg rcvr);
Ref FPointToWord(RefArg rcvr);
Ref FPointsToArray(RefArg rcvr);
Ref FPositionCaret(RefArg rcvr);
Ref FPostAndDo(RefArg rcvr);
Ref FPostCommand(RefArg rcvr);
Ref FPostCommandParam(RefArg rcvr);
Ref FPostKeyString(RefArg rcvr);
Ref FPurgeAreaCache(RefArg rcvr);
Ref FRectsOverlap(RefArg rcvr);
Ref FRedoChildrenX(RefArg rcvr);
Ref FRegisterGestalt(RefArg rcvr);
Ref FRegisterOpenKeyboard(RefArg rcvr);
Ref FRelBounds(RefArg rcvr);
Ref FRemoveStepView(RefArg rcvr);
Ref FRemoveView(RefArg rcvr);
Ref FReplaceGestalt(RefArg rcvr);
Ref FRestoreKeyView(RefArg rcvr);
Ref FRevealEffectX(RefArg rcvr);
Ref FSectRect(RefArg rcvr);
Ref FSendKeyMessage(RefArg rcvr);
Ref FSetBounds(RefArg rcvr);
Ref FSetCalibration(RefArg rcvr);
Ref FSetCaretInfo(RefArg rcvr);
Ref FSetClipboard(RefArg rcvr);
Ref FSetHiliteNoUpdateX(RefArg rcvr);
Ref FSetHiliteX(RefArg rcvr);
Ref FSetKeyView(RefArg rcvr);
Ref FSetOriginX(RefArg rcvr);
Ref FSetPopup(RefArg rcvr);
Ref FSetRemoteWriting(RefArg rcvr);
Ref FSetSysAlarm(RefArg rcvr);
Ref FSetupIdleX(RefArg rcvr);
Ref FShapeBounds(RefArg rcvr);
Ref FShowCaret(RefArg rcvr);
Ref FShowX(RefArg rcvr);
Ref FSlideEffectX(RefArg rcvr);
Ref FStartBypassTablet(RefArg rcvr);
Ref FStopBypassTablet(RefArg rcvr);
Ref FStrokeBounds(RefArg rcvr);
Ref FStrokeDone(RefArg rcvr);
Ref FStrokeInPicture(RefArg rcvr);
Ref FSyncChildrenX(RefArg rcvr);
Ref FSyncScrollX(RefArg rcvr);
Ref FSyncViewX(RefArg rcvr);
Ref FTabletBufferEmpty(RefArg rcvr);
Ref FToggleX(RefArg rcvr);
Ref FTopicByName(RefArg rcvr);
Ref FTrackButtonX(RefArg rcvr);
Ref FTrackHiliteX(RefArg rcvr);
Ref FTranslateKey(RefArg rcvr);
Ref FUnionRect(RefArg rcvr);
Ref FUnregisterOpenKeyboard(RefArg rcvr);
Ref FViewAutopsy(RefArg rcvr);
Ref FViewContainsCaretView(RefArg rcvr);
Ref FVisibleBox(RefArg rcvr);
Ref FVoteOnWordUnit(RefArg rcvr);
Ref FYieldToFork(RefArg rcvr);
Ref FpkgDownload(RefArg rcvr);
}

NS_STUB(FAddDelayedCall, RefArg rcvr)
NS_STUB(FAddDelayedSend, RefArg rcvr)
NS_STUB(FAddKeyCommand, RefArg rcvr)
NS_STUB(FAddKeyCommands, RefArg rcvr)
NS_STUB(FAddStepView, RefArg rcvr)
NS_STUB(FAddUndoAction, RefArg rcvr)
NS_STUB(FAddUndoCall, RefArg rcvr)
NS_STUB(FAddUndoSend, RefArg rcvr)
NS_STUB(FAddView, RefArg rcvr)
NS_STUB(FArrayToPoints, RefArg rcvr)
NS_STUB(FBlockKeyCommand, RefArg rcvr)
NS_STUB(FBookAvailable, RefArg rcvr)
NS_STUB(FBookRemoved, RefArg rcvr)
NS_STUB(FBuildContext, RefArg rcvr)
NS_STUB(FBusyBoxControl, RefArg rcvr)
NS_STUB(FCalibrateTablet, RefArg rcvr)
NS_STUB(FCaretRelativeToVisibleRect, RefArg rcvr)
NS_STUB(FCategorizeKeyCommands, RefArg rcvr)
NS_STUB(FChangeStylesOfRange, RefArg rcvr)
NS_STUB(FChildViewFramesX, RefArg rcvr)
NS_STUB(FClearHardKeymap, RefArg rcvr)
NS_STUB(FClearPopup, RefArg rcvr)
NS_STUB(FClearUndoStacks, RefArg rcvr)
NS_STUB(FClipboardCommand, RefArg rcvr)
NS_STUB(FCloseX, RefArg rcvr)
NS_STUB(FCommandKeyboardConnected, RefArg rcvr)
NS_STUB(FCountGesturePoints, RefArg rcvr)
NS_STUB(FCurrentExports, RefArg rcvr)
NS_STUB(FCurrentImports, RefArg rcvr)
NS_STUB(FDV, RefArg rcvr)
NS_STUB(FDebug, RefArg rcvr)
NS_STUB(FDebugMemoryStats, RefArg rcvr)
NS_STUB(FDebugRunUntilIdle, RefArg rcvr)
NS_STUB(FDeleteX, RefArg rcvr)
NS_STUB(FDirtyBoxX, RefArg rcvr)
NS_STUB(FDirtyX, RefArg rcvr)
NS_STUB(FDismissPopup, RefArg rcvr)
NS_STUB(FDisplaySplashGraphic, RefArg rcvr)
NS_STUB(FDoDrawing, RefArg rcvr)
NS_STUB(FDoPopup, RefArg rcvr)
NS_STUB(FDoScrubEffect, RefArg rcvr)
NS_STUB(FDragAndDrop, RefArg rcvr)
NS_STUB(FDragAndDropLtd, RefArg rcvr)
NS_STUB(FDragX, RefArg rcvr)
NS_STUB(FDrawPolygons, RefArg rcvr)
NS_STUB(FDrawShape, RefArg rcvr)
NS_STUB(FDropHilites, RefArg rcvr)
NS_STUB(FEffectX, RefArg rcvr)
NS_STUB(FEventPause, RefArg rcvr)
NS_STUB(FExitModalDialog, RefArg rcvr)
NS_STUB(FExtractData, RefArg rcvr)
NS_STUB(FExtractRangeAsRichString, RefArg rcvr)
NS_STUB(FExtractTextRange, RefArg rcvr)
NS_STUB(FFilterDialog, RefArg rcvr)
NS_STUB(FFindKeyCommand, RefArg rcvr)
NS_STUB(FFlushImports, RefArg rcvr)
NS_STUB(FForkScript, RefArg rcvr)
NS_STUB(FFulfillImportTable, RefArg rcvr)
NS_STUB(FGatherKeyCommands, RefArg rcvr)
NS_STUB(FGestalt, RefArg rcvr)
NS_STUB(FGesturePoint, RefArg rcvr)
NS_STUB(FGestureType, RefArg rcvr)
NS_STUB(FGetAlternates, RefArg rcvr)
NS_STUB(FGetCalibration, RefArg rcvr)
NS_STUB(FGetCaretBox, RefArg rcvr)
NS_STUB(FGetCaretInfo, RefArg rcvr)
NS_STUB(FGetClipboard, RefArg rcvr)
NS_STUB(FGetClipboardIcon, RefArg rcvr)
NS_STUB(FGetDrawBoxX, RefArg rcvr)
NS_STUB(FGetFlags, RefArg rcvr)
NS_STUB(FGetFrameStuff, RefArg rcvr)
NS_STUB(FGetHiliteOffsets, RefArg rcvr)
NS_STUB(FGetId, RefArg rcvr)
NS_STUB(FGetInkWordInfo, RefArg rcvr)
NS_STUB(FGetKeyView, RefArg rcvr)
NS_STUB(FGetPackages, RefArg rcvr)
NS_STUB(FGetPoint, RefArg rcvr)
NS_STUB(FGetPointsArray, RefArg rcvr)
NS_STUB(FGetPointsArrayXY, RefArg rcvr)
NS_STUB(FGetPolygons, RefArg rcvr)
NS_STUB(FGetPopup, RefArg rcvr)
NS_STUB(FGetRemoteWriting, RefArg rcvr)
// nil until there is a root view (plan step 9.2); the NS Debug Tools expect it
NS_STUB_NIL_OK(FGetRoot, RefArg rcvr)
NS_STUB(FGetScoreArray, RefArg rcvr)
NS_STUB(FGetStyleAtOffset, RefArg rcvr)
NS_STUB(FGetStylesOfRange, RefArg rcvr)
NS_STUB(FGetTextFlags, RefArg rcvr)
NS_STUB(FGetTrueModifiers, RefArg rcvr)
NS_STUB(FGetUndoState, RefArg rcvr)
NS_STUB(FGetUnitDownTime, RefArg rcvr)
NS_STUB(FGetUnitEndTime, RefArg rcvr)
NS_STUB(FGetUnitStartTime, RefArg rcvr)
NS_STUB(FGetUnitUpTime, RefArg rcvr)
NS_STUB(FGetView, RefArg rcvr)
NS_STUB(FGetWordArray, RefArg rcvr)
NS_STUB(FGlobalBoxX, RefArg rcvr)
NS_STUB(FGlobalOuterBoxX, RefArg rcvr)
NS_STUB(FHandleInkWord, RefArg rcvr)
NS_STUB(FHandleInsertItems, RefArg rcvr)
NS_STUB(FHandleKeyEvents, RefArg rcvr)
NS_STUB(FHandleRawInk, RefArg rcvr)
NS_STUB(FHandleUnit, RefArg rcvr)
NS_STUB(FHideCaret, RefArg rcvr)
NS_STUB(FHideX, RefArg rcvr)
NS_STUB(FHiliteOwner, RefArg rcvr)
NS_STUB(FHiliteUniqueX, RefArg rcvr)
NS_STUB(FHiliteViewChildren, RefArg rcvr)
NS_STUB(FHiliteX, RefArg rcvr)
NS_STUB(FHiliter, RefArg rcvr)
NS_STUB(FHobbleTablet, RefArg rcvr)
NS_STUB(FInRepeatedKeyCommand, RefArg rcvr)
NS_STUB(FInkOff, RefArg rcvr)
NS_STUB(FInkOffUnHobbled, RefArg rcvr)
NS_STUB(FInkOn, RefArg rcvr)
NS_STUB(FInsertItemsAtCaret, RefArg rcvr)
NS_STUB(FInsertTabletSample, RefArg rcvr)
NS_STUB(FInsetRect, RefArg rcvr)
NS_STUB(FInvertRect, RefArg rcvr)
NS_STUB(FIsCommandKeystroke, RefArg rcvr)
NS_STUB(FIsKeyDown, RefArg rcvr)
NS_STUB(FIsPrimShape, RefArg rcvr)
NS_STUB(FIsPtInRect, RefArg rcvr)
NS_STUB(FIsTabletCalibrationNeeded, RefArg rcvr)
NS_STUB(FJournalReplayALine, RefArg rcvr)
NS_STUB(FJournalReplayAStroke, RefArg rcvr)
NS_STUB(FJournalReplayBusy, RefArg rcvr)
NS_STUB(FJournalReplayStrokes, RefArg rcvr)
NS_STUB(FJournalStartRecord, RefArg rcvr)
NS_STUB(FJournalStopRecord, RefArg rcvr)
NS_STUB(FKeyIn, RefArg rcvr)
NS_STUB(FKeyboardConnected, RefArg rcvr)
NS_STUB(FLayoutTableX, RefArg rcvr)
NS_STUB(FLayoutVerticallyX, RefArg rcvr)
NS_STUB(FLoadFontCache, RefArg rcvr)
NS_STUB(FLocalBoxX, RefArg rcvr)
NS_STUB(FMakeBitmap, RefArg rcvr)
NS_STUB(FMakeLine, RefArg rcvr)
NS_STUB(FMakeRect, RefArg rcvr)
NS_STUB(FMakeShape, RefArg rcvr)
NS_STUB(FMakeText, RefArg rcvr)
NS_STUB(FMakeTextBox, RefArg rcvr)
NS_STUB(FMakeTextLines, RefArg rcvr)
NS_STUB(FMatchKeyMessage, RefArg rcvr)
NS_STUB(FModalDialog, RefArg rcvr)
NS_STUB(FModalRecognitionOff, RefArg rcvr)
NS_STUB(FModalRecognitionOn, RefArg rcvr)
NS_STUB(FModalState, RefArg rcvr)
NS_STUB(FMoveBehindX, RefArg rcvr)
NS_STUB(FNTKAlive, RefArg rcvr)
NS_STUB(FNTKDownload, RefArg rcvr)
NS_STUB(FNTKListener, RefArg rcvr)
NS_STUB(FNTKSend, RefArg rcvr)
NS_STUB(FNextKeyView, RefArg rcvr)
NS_STUB(FOffsetRect, RefArg rcvr)
NS_STUB(FOffsetShape, RefArg rcvr)
NS_STUB(FOffsetView, RefArg rcvr)
NS_STUB(FParentX, RefArg rcvr)
NS_STUB(FPenPos, RefArg rcvr)
NS_STUB(FPendingImports, RefArg rcvr)
NS_STUB(FPickViewKeyDown, RefArg rcvr)
NS_STUB(FPointToCharOffset, RefArg rcvr)
NS_STUB(FPointToWord, RefArg rcvr)
NS_STUB(FPointsToArray, RefArg rcvr)
NS_STUB(FPositionCaret, RefArg rcvr)
NS_STUB(FPostAndDo, RefArg rcvr)
NS_STUB(FPostCommand, RefArg rcvr)
NS_STUB(FPostCommandParam, RefArg rcvr)
NS_STUB(FPostKeyString, RefArg rcvr)
NS_STUB(FPurgeAreaCache, RefArg rcvr)
NS_STUB(FRectsOverlap, RefArg rcvr)
NS_STUB(FRedoChildrenX, RefArg rcvr)
NS_STUB(FRegisterGestalt, RefArg rcvr)
NS_STUB(FRegisterOpenKeyboard, RefArg rcvr)
NS_STUB(FRelBounds, RefArg rcvr)
NS_STUB(FRemoveStepView, RefArg rcvr)
NS_STUB(FRemoveView, RefArg rcvr)
NS_STUB(FReplaceGestalt, RefArg rcvr)
NS_STUB(FRestoreKeyView, RefArg rcvr)
NS_STUB(FRevealEffectX, RefArg rcvr)
NS_STUB(FSectRect, RefArg rcvr)
NS_STUB(FSendKeyMessage, RefArg rcvr)
NS_STUB(FSetBounds, RefArg rcvr)
NS_STUB(FSetCalibration, RefArg rcvr)
NS_STUB(FSetCaretInfo, RefArg rcvr)
NS_STUB(FSetClipboard, RefArg rcvr)
NS_STUB(FSetHiliteNoUpdateX, RefArg rcvr)
NS_STUB(FSetHiliteX, RefArg rcvr)
NS_STUB(FSetKeyView, RefArg rcvr)
NS_STUB(FSetOriginX, RefArg rcvr)
NS_STUB(FSetPopup, RefArg rcvr)
NS_STUB(FSetRemoteWriting, RefArg rcvr)
NS_STUB(FSetSysAlarm, RefArg rcvr)
NS_STUB(FSetupIdleX, RefArg rcvr)
NS_STUB(FShapeBounds, RefArg rcvr)
NS_STUB(FShowCaret, RefArg rcvr)
NS_STUB(FShowX, RefArg rcvr)
NS_STUB(FSlideEffectX, RefArg rcvr)
NS_STUB(FStartBypassTablet, RefArg rcvr)
NS_STUB(FStopBypassTablet, RefArg rcvr)
NS_STUB(FStrokeBounds, RefArg rcvr)
NS_STUB(FStrokeDone, RefArg rcvr)
NS_STUB(FStrokeInPicture, RefArg rcvr)
NS_STUB(FSyncChildrenX, RefArg rcvr)
NS_STUB(FSyncScrollX, RefArg rcvr)
NS_STUB(FSyncViewX, RefArg rcvr)
NS_STUB(FTabletBufferEmpty, RefArg rcvr)
NS_STUB(FToggleX, RefArg rcvr)
NS_STUB(FTopicByName, RefArg rcvr)
NS_STUB(FTrackButtonX, RefArg rcvr)
NS_STUB(FTrackHiliteX, RefArg rcvr)
NS_STUB(FTranslateKey, RefArg rcvr)
NS_STUB(FUnionRect, RefArg rcvr)
NS_STUB(FUnregisterOpenKeyboard, RefArg rcvr)
NS_STUB(FViewAutopsy, RefArg rcvr)
NS_STUB(FViewContainsCaretView, RefArg rcvr)
NS_STUB(FVisibleBox, RefArg rcvr)
NS_STUB(FVoteOnWordUnit, RefArg rcvr)
NS_STUB(FYieldToFork, RefArg rcvr)
NS_STUB(FpkgDownload, RefArg rcvr)
