#include "Objects.h"
#include "Unimplemented.h"
#include "Globals.h"

#if !defined(forNTK)
extern "C" {
Ref FDefineGlobalConstant(RefArg inRcvr, RefArg inTag, RefArg inObj);
Ref FUnDefineGlobalConstant(RefArg inRcvr, RefArg inTag);
Ref FDefPureFn(RefArg inRcvr, RefArg inTag, RefArg inFn);
Ref FStuffHex(RefArg inRcvr, RefArg inHexStr, RefArg inClass);
Ref ReadStreamFile(RefArg inRcvr, RefArg inFilename);
}
#include "protoProtoEditor.h"

NS_STUB(FDefineGlobalConstant, RefArg inRcvr, RefArg inTag, RefArg inObj)
NS_STUB(FUnDefineGlobalConstant, RefArg inRcvr, RefArg inTag)
NS_STUB(FDefPureFn, RefArg inRcvr, RefArg inTag, RefArg inFn)
NS_STUB(FStuffHex, RefArg rcvr, RefArg inHexStr, RefArg inClass)
NS_STUB(ReadStreamFile, RefArg inRcvr, RefArg inFilename)

NS_STUB(Selection, RefArg inRcvr)
NS_STUB(SelectionOffset, RefArg inRcvr)
NS_STUB(SelectionLength, RefArg inRcvr)
NS_STUB(SetSelection, RefArg inRcvr, RefArg inStart, RefArg inLength)
NS_STUB(ReplaceSelection, RefArg inRcvr, RefArg inString)
NS_STUB(TextString, RefArg inRcvr)
NS_STUB(TextLength, RefArg inRcvr)
NS_STUB(FindLine, RefArg inRcvr, RefArg inOffset)
NS_STUB(LineStart, RefArg inRcvr, RefArg inLine)
NS_STUB(NumberOfLines, RefArg inRcvr)
NS_STUB(LineTop, RefArg inRcvr, RefArg inLine)
NS_STUB(LineBottom, RefArg inRcvr, RefArg inLine)
NS_STUB(LineBaseline, RefArg inRcvr, RefArg inLine)
NS_STUB(LeftEdge, RefArg inRcvr, RefArg inOffset)
NS_STUB(RightEdge, RefArg inRcvr, RefArg inOffset)
NS_STUB(PointToOffset, RefArg inRcvr, RefArg inH, RefArg inV)
NS_STUB(MapChars, RefArg inRcvr, RefArg inClosure, RefArg inStart, RefArg inLength)
NS_STUB(SearchChars, RefArg inRcvr, RefArg inClosure, RefArg inStart, RefArg inLength)
NS_STUB(Peek, RefArg inRcvr, RefArg inOffset)
NS_STUB(SetKeyHandler, RefArg inRcvr, RefArg inKey, RefArg inSymbol)
NS_STUB(GetKeyHandler, RefArg inRcvr, RefArg inKey)
NS_STUB(SetMetaBit, RefArg inRcvr)
NS_STUB(QuoteCharacter, RefArg inRcvr)
NS_STUB(CharacterClass, RefArg inRcvr, RefArg inChar)
NS_STUB(SetCharacterClass, RefArg inRcvr, RefArg inChar, RefArg inClass)
NS_STUB(TokenStart, RefArg inRcvr, RefArg inOffset)
NS_STUB(TokenEnd, RefArg inRcvr, RefArg inOffset)
NS_STUB(TellUser, RefArg inRcvr, RefArg inString)
NS_STUB(VisibleTop, RefArg inRcvr)
NS_STUB(VisibleLeft, RefArg inRcvr)
NS_STUB(VisibleHeight, RefArg inRcvr)
NS_STUB(VisibleWidth, RefArg inRcvr)
NS_STUB(SetVisibleTop, RefArg inRcvr, RefArg inNewTop)
NS_STUB(SetVisibleLeft, RefArg inRcvr, RefArg inNewLeft)
#endif

extern "C" {
Ref AddBookmark(RefArg rcvr);
Ref AddHistory(RefArg rcvr);
Ref AddInkMarks(RefArg rcvr);
Ref AddToContentArea(RefArg rcvr);
Ref Append(RefArg rcvr);
Ref AuthorData(RefArg rcvr);
Ref BookClosed(RefArg rcvr);
Ref BookTitle(RefArg rcvr);
Ref Bookmarks(RefArg rcvr);
Ref CFDispose(RefArg rcvr);
Ref CFInstantiate(RefArg rcvr);
Ref CFRecord(RefArg rcvr);
Ref CIAbort(RefArg rcvr);
Ref CIAccept(RefArg rcvr);
Ref CIBytesAvailable(RefArg rcvr);
Ref CICaller(RefArg rcvr);
Ref CIConnect(RefArg rcvr);
Ref CIDisconnect(RefArg rcvr);
Ref CIDispose(RefArg rcvr);
Ref CIDisposeLeavingTEndpoint(RefArg rcvr);
Ref CIFlushInput(RefArg rcvr);
Ref CIFlushOutput(RefArg rcvr);
Ref CIFlushPartial(RefArg rcvr);
Ref CIGetOptions(RefArg rcvr);
Ref CIInput(RefArg rcvr);
Ref CIInputAvailable(RefArg rcvr);
Ref CIInstantiate(RefArg rcvr);
Ref CIInstantiateFromEndpoint(RefArg rcvr);
Ref CIJustBind(RefArg rcvr);
Ref CIJustClose(RefArg rcvr);
Ref CIJustConnect(RefArg rcvr);
Ref CIJustDisconnect(RefArg rcvr);
Ref CIJustListen(RefArg rcvr);
Ref CIJustOpen(RefArg rcvr);
Ref CIJustRelease(RefArg rcvr);
Ref CIJustUnBind(RefArg rcvr);
Ref CIListen(RefArg rcvr);
Ref CINewAbort(RefArg rcvr);
Ref CINewAccept(RefArg rcvr);
Ref CINewBind(RefArg rcvr);
Ref CINewConnect(RefArg rcvr);
Ref CINewDisconnect(RefArg rcvr);
Ref CINewDispose(RefArg rcvr);
Ref CINewDisposeLeavingTEndpoint(RefArg rcvr);
Ref CINewDisposeLeavingTool(RefArg rcvr);
Ref CINewFlushInput(RefArg rcvr);
Ref CINewFlushPartial(RefArg rcvr);
Ref CINewInput(RefArg rcvr);
Ref CINewInstantiate(RefArg rcvr);
Ref CINewInstantiateFromEndpoint(RefArg rcvr);
Ref CINewListen(RefArg rcvr);
Ref CINewOption(RefArg rcvr);
Ref CINewOutput(RefArg rcvr);
Ref CINewPartial(RefArg rcvr);
Ref CINewSetInputSpec(RefArg rcvr);
Ref CINewSetState(RefArg rcvr);
Ref CINewState(RefArg rcvr);
Ref CINewUnBind(RefArg rcvr);
Ref CIOutput(RefArg rcvr);
Ref CIOutputDone(RefArg rcvr);
Ref CIOutputFrame(RefArg rcvr);
Ref CIPartial(RefArg rcvr);
Ref CIReadyForOutput(RefArg rcvr);
Ref CIReject(RefArg rcvr);
Ref CIRelease(RefArg rcvr);
Ref CIRequestsPending(RefArg rcvr);
Ref CISNewInstantiate(RefArg rcvr);
Ref CISNewInstantiateFromEndpoint(RefArg rcvr);
Ref CISStreamIn(RefArg rcvr);
Ref CISStreamOut(RefArg rcvr);
Ref CISetInputSpec(RefArg rcvr);
Ref CISetOptions(RefArg rcvr);
Ref CISetSync(RefArg rcvr);
Ref CIStartCCL(RefArg rcvr);
Ref CIState(RefArg rcvr);
Ref CIStopCCL(RefArg rcvr);
Ref CSDispose(RefArg rcvr);
Ref CSGetDefaultConfig(RefArg rcvr);
Ref CSInstantiate(RefArg rcvr);
Ref CSSetDefaultConfig(RefArg rcvr);
Ref CallOnlineServices(RefArg rcvr);
Ref CheezyIntersect(RefArg rcvr);
Ref CheezySubsumption(RefArg rcvr);
Ref CircleDistance(RefArg rcvr);
Ref CleanString(RefArg rcvr);
Ref CommonAncestors(RefArg rcvr);
Ref CompositeClass(RefArg rcvr);
Ref CoordinateToLatitude(RefArg rcvr);
Ref CoordinateToLongitude(RefArg rcvr);
Ref CorrectSelect(RefArg rcvr);
Ref CorrectWord(RefArg rcvr);
Ref CountPages(RefArg rcvr);
Ref CuFind(RefArg rcvr);
Ref CurrentBook(RefArg rcvr);
Ref CurrentKiosk(RefArg rcvr);
Ref CurrentPage(RefArg rcvr);
Ref DisconnectOnlineServices(RefArg rcvr);
Ref DumpDict(RefArg rcvr);
Ref EWBufferStart(RefArg rcvr);
Ref EWConnectToHost(RefArg rcvr);
Ref EWDecodePacket(RefArg rcvr);
Ref EWEscape(RefArg rcvr);
Ref EWFileToFrame(RefArg rcvr);
Ref EWFrameToFile(RefArg rcvr);
Ref EWGetData(RefArg rcvr);
Ref EWGetError(RefArg rcvr);
Ref EWGetMacHeader(RefArg rcvr);
Ref EWInstantiate(RefArg rcvr);
Ref EWOutput(RefArg rcvr);
Ref EWOutputAtom(RefArg rcvr);
Ref EWSend(RefArg rcvr);
Ref EWSetError(RefArg rcvr);
Ref EWUnEscape(RefArg rcvr);
Ref EWUniAtomHandler(RefArg rcvr);
Ref EWUploadFile(RefArg rcvr);
Ref FActivate1XPackage(RefArg rcvr);
Ref FAddCapitalizedEntry(RefArg rcvr);
Ref FAddUnitInfo(RefArg rcvr);
Ref FAddWordInfo(RefArg rcvr);
Ref FAdjustParagraph(RefArg rcvr);
Ref FAutoAdd(RefArg rcvr);
Ref FAutoRemove(RefArg rcvr);
Ref FChildTemplateFromTopic(RefArg rcvr);
Ref FClearCorrectionInfo(RefArg rcvr);
Ref FClearWordInfoFlags(RefArg rcvr);
Ref FClickLetterShapes(RefArg rcvr);
Ref FCloseRemote(RefArg rcvr);
Ref FCollapseTopic(RefArg rcvr);
Ref FConnAbort(RefArg rcvr);
Ref FConnBytesAvailable(RefArg rcvr);
Ref FConnConnect(RefArg rcvr);
Ref FConnDesktopType(RefArg rcvr);
Ref FConnDoConnection(RefArg rcvr);
Ref FConnDoKeyboardPassthrough(RefArg rcvr);
Ref FConnFlushCommandData(RefArg rcvr);
Ref FConnGetCurrentStore(RefArg rcvr);
Ref FConnGetSyncChanges(RefArg rcvr);
Ref FConnInstallProtocolExtension(RefArg rcvr);
Ref FConnInstantiate(RefArg rcvr);
Ref FConnReadBytes(RefArg rcvr);
Ref FConnReadCommand(RefArg rcvr);
Ref FConnReadCommandData(RefArg rcvr);
Ref FConnReadCommandHeader(RefArg rcvr);
Ref FConnRemoveProtocolExtension(RefArg rcvr);
Ref FConnRetryPassword(RefArg rcvr);
Ref FConnSetState(RefArg rcvr);
Ref FConnStop(RefArg rcvr);
Ref FConnWriteBytes(RefArg rcvr);
Ref FConnWriteCommand(RefArg rcvr);
Ref FConnWriteCommandHeader(RefArg rcvr);
Ref FConnectionState(RefArg rcvr);
Ref FCountLetterShapes(RefArg rcvr);
Ref FDeActivate1XPackage(RefArg rcvr);
Ref FDeleteStoreObject(RefArg rcvr);
Ref FDestroyProtocol(RefArg rcvr);
Ref FDispatchProtocol(RefArg rcvr);
Ref FDoEntryLearning(RefArg rcvr);
Ref FDrawExpando(RefArg rcvr);
Ref FDrawLetterShapes(RefArg rcvr);
Ref FExpandTopic(RefArg rcvr);
Ref FExtractRange(RefArg rcvr);
Ref FFindDictionaryFrame(RefArg rcvr);
Ref FFindNewInfo(RefArg rcvr);
Ref FFindWordInfo(RefArg rcvr);
Ref FForLoop(RefArg rcvr);
Ref FGetBinaryCompander(RefArg rcvr);
Ref FGetBinaryCompanderData(RefArg rcvr);
Ref FGetBinaryStore(RefArg rcvr);
Ref FGetBinaryStoredSize(RefArg rcvr);
Ref FGetCapability(RefArg rcvr);
Ref FGetChannelInputGain(RefArg rcvr);
Ref FGetChannelVolume(RefArg rcvr);
Ref FGetHiliteWeight(RefArg rcvr);
Ref FGetSiblingSlot(RefArg rcvr);
Ref FGetStoreCardSlot(RefArg rcvr);
Ref FGetStoreCardType(RefArg rcvr);
Ref FGetStoreObjectSize(RefArg rcvr);
Ref FGetValue(RefArg rcvr);
Ref FGetWordInfo(RefArg rcvr);
Ref FGetWordList(RefArg rcvr);
Ref FHasCapability(RefArg rcvr);
Ref FHasSiblingSlot(RefArg rcvr);
Ref FInsertRange(RefArg rcvr);
Ref FIsCollapsed(RefArg rcvr);
Ref FIsLargeBinary(RefArg rcvr);
Ref FKeyHelpSlipDraw(RefArg rcvr);
Ref FKeyHelpSlipSetup(RefArg rcvr);
Ref FKeyboardInputX(RefArg rcvr);
Ref FLBClearCache(RefArg rcvr);
Ref FListBottom(RefArg rcvr);
Ref FLocalVar(RefArg rcvr);
Ref FMakeDragRef(RefArg rcvr);
Ref FMakeWordInfo(RefArg rcvr);
Ref FMarkerBounds(RefArg rcvr);
Ref FMergeWordInfo(RefArg rcvr);
Ref FMoveWordFirst(RefArg rcvr);
Ref FMungeStyles(RefArg rcvr);
Ref FNewProtocol(RefArg rcvr);
Ref FNewStoreObject(RefArg rcvr);
Ref FNextClassInfo(RefArg rcvr);
Ref FOffsetCorrectionInfo(RefArg rcvr);
Ref FOpenRemote(RefArg rcvr);
Ref FPickViewGetScollerValues(RefArg rcvr);
Ref FPickViewScroll(RefArg rcvr);
Ref FProcessBuiltinCommand(RefArg rcvr);
Ref FProtocolImplementationName(RefArg rcvr);
Ref FProtocolInterfaceName(RefArg rcvr);
Ref FProtocolSignature(RefArg rcvr);
Ref FProtocolVersion(RefArg rcvr);
Ref FReadStoreObject(RefArg rcvr);
Ref FReboot(RefArg rcvr);
Ref FRemove1XPackage(RefArg rcvr);
Ref FRemoveCorrectionInfo(RefArg rcvr);
Ref FRemoveToggledEntries(RefArg rcvr);
Ref FResetLearningDefaults(RefArg rcvr);
Ref FSendCode(RefArg rcvr);
Ref FSetChannelInputGain(RefArg rcvr);
Ref FSetChannelVolume(RefArg rcvr);
Ref FSetHiliteWeight(RefArg rcvr);
Ref FSetStoreObjectSize(RefArg rcvr);
Ref FSetWordInfoFlags(RefArg rcvr);
Ref FSetWordList(RefArg rcvr);
Ref FSetupTetheredListener(RefArg rcvr);
Ref FSetupVisibleChildren(RefArg rcvr);
Ref FSoundClose(RefArg rcvr);
Ref FSoundIsActive(RefArg rcvr);
Ref FSoundIsPaused(RefArg rcvr);
Ref FSoundOpen(RefArg rcvr);
Ref FSoundPause(RefArg rcvr);
Ref FSoundSchedule(RefArg rcvr);
Ref FSoundStart(RefArg rcvr);
Ref FSoundStop(RefArg rcvr);
Ref FStoreAbort(RefArg rcvr);
Ref FStringToFrameMapper(RefArg rcvr);
Ref FSuckPackageFromBinary(RefArg rcvr);
Ref FSuckPackageFromEnpoint(RefArg rcvr);
Ref FSuckPackageOffDeskTop(RefArg rcvr);
Ref FTXChangeRangeRulers(RefArg rcvr);
Ref FTXChangeRangeRuns(RefArg rcvr);
Ref FTXCharToPoint(RefArg rcvr);
Ref FTXClear(RefArg rcvr);
Ref FTXCopy(RefArg rcvr);
Ref FTXCut(RefArg rcvr);
Ref FTXExternalize(RefArg rcvr);
Ref FTXFinderFindString(RefArg rcvr);
Ref FTXFinderGetCountCharacters(RefArg rcvr);
Ref FTXFinderGetRangeText(RefArg rcvr);
Ref FTXGetContinuousRun(RefArg rcvr);
Ref FTXGetCountCharacters(RefArg rcvr);
Ref FTXGetCountPages(RefArg rcvr);
Ref FTXGetHiliteRange(RefArg rcvr);
Ref FTXGetLineRange(RefArg rcvr);
Ref FTXGetParagraphRange(RefArg rcvr);
Ref FTXGetRangeData(RefArg rcvr);
Ref FTXGetScrollValues(RefArg rcvr);
Ref FTXGetTextViewRect(RefArg rcvr);
Ref FTXGetTotalHeight(RefArg rcvr);
Ref FTXGetTotalWidth(RefArg rcvr);
Ref FTXGetWordRange(RefArg rcvr);
Ref FTXHideRuler(RefArg rcvr);
Ref FTXInsertPageBreak(RefArg rcvr);
Ref FTXInternalize(RefArg rcvr);
Ref FTXIsModified(RefArg rcvr);
Ref FTXIsRulerShown(RefArg rcvr);
Ref FTXPaste(RefArg rcvr);
Ref FTXPointToChar(RefArg rcvr);
Ref FTXReplace(RefArg rcvr);
Ref FTXReplaceAll(RefArg rcvr);
Ref FTXScroll(RefArg rcvr);
Ref FTXSetDrawOrigin(RefArg rcvr);
Ref FTXSetGeometry(RefArg rcvr);
Ref FTXSetHiliteRange(RefArg rcvr);
Ref FTXSetReadOnly(RefArg rcvr);
Ref FTXSetStore(RefArg rcvr);
Ref FTXShowRuler(RefArg rcvr);
Ref FTXUpdateRulerInfo(RefArg rcvr);
Ref FTXViewFindString(RefArg rcvr);
Ref FTestWordInfoFlags(RefArg rcvr);
Ref FTopicBottom(RefArg rcvr);
Ref FTopicIndexToView(RefArg rcvr);
Ref FVisibleTopicIndex(RefArg rcvr);
Ref FWriteEntireStoreObject(RefArg rcvr);
Ref FWriteStoreObject(RefArg rcvr);
Ref FastStringLookup(RefArg rcvr);
Ref FavorAction(RefArg rcvr);
Ref FavorObject(RefArg rcvr);
Ref Fdim(RefArg rcvr);
Ref FindContentBySlot(RefArg rcvr);
Ref FindContentByValue(RefArg rcvr);
Ref FindPageByContent(RefArg rcvr);
Ref FindPageBySubject(RefArg rcvr);
Ref FindPageByValue(RefArg rcvr);
Ref FormatVertical(RefArg rcvr);
Ref GenPhoneTypeList(RefArg rcvr);
Ref GeneratePhrases(RefArg rcvr);
Ref GenerateSubstrings(RefArg rcvr);
Ref GetDictItem(RefArg rcvr);
Ref GetRelevantTemplates(RefArg rcvr);
Ref GlueStrings(RefArg rcvr);
Ref GuessAddressee(RefArg rcvr);
Ref HiliteBlock(RefArg rcvr);
Ref History(RefArg rcvr);
Ref IASmartCFLookup(RefArg rcvr);
Ref ISATest(RefArg rcvr);
Ref InkMarks(RefArg rcvr);
Ref LatitudeToCoordinate(RefArg rcvr);
Ref LayoutMeeting(RefArg rcvr);
Ref LexDateLookup(RefArg rcvr);
Ref LexPhoneLookup(RefArg rcvr);
Ref LexTimeLookup(RefArg rcvr);
Ref LongitudeToCoordinate(RefArg rcvr);
Ref MakeLowerCase(RefArg rcvr);
Ref MakePhrasalLexEntry(RefArg rcvr);
Ref MapSymToFrame(RefArg rcvr);
Ref PageContents(RefArg rcvr);
Ref PageScroll(RefArg rcvr);
Ref PageThumbnail(RefArg rcvr);
Ref PathToRoot(RefArg rcvr);
Ref PhoneIndexToValue(RefArg rcvr);
Ref PhoneStringToValue(RefArg rcvr);
Ref PhoneSymToIndex(RefArg rcvr);
Ref PhoneSymToString(RefArg rcvr);
Ref PhraseFilter(RefArg rcvr);
Ref PrefixP(RefArg rcvr);
Ref PrepBook(RefArg rcvr);
Ref PrepRecConfig(RefArg rcvr);
Ref PreviousPage(RefArg rcvr);
Ref ReFlow(RefArg rcvr);
Ref ReadDomainOptions(RefArg rcvr);
Ref ReflowPreflight(RefArg rcvr);
Ref RefreshTopics(RefArg rcvr);
Ref RegisterBookRef(RefArg rcvr);
Ref ScrollToCurrent(RefArg rcvr);
Ref SendAbort(RefArg rcvr);
Ref StartIRSniffing(RefArg rcvr);
Ref StopIRSniffing(RefArg rcvr);
Ref Store1XPackageToVBO(RefArg rcvr);
Ref StoreConvertSoupSortTables(RefArg rcvr);
Ref StorePackageRestore(RefArg rcvr);
Ref StoreSegmentedPackageRestore(RefArg rcvr);
Ref SuffixP(RefArg rcvr);
Ref TableLookup(RefArg rcvr);
Ref TurnToContent(RefArg rcvr);
Ref TurnToPage(RefArg rcvr);
Ref UnionSoupFlush(RefArg rcvr);
Ref UniqueAppendList(RefArg rcvr);
Ref UniqueAppendListGen(RefArg rcvr);
Ref UnmatchedWords(RefArg rcvr);
Ref UnregisterBookRef(RefArg rcvr);
Ref UpdateBookmarks(RefArg rcvr);
Ref UseTrainingDataForRecognition(RefArg rcvr);
Ref WhereIsBook(RefArg rcvr);
Ref ZapCancel(RefArg rcvr);
Ref ZapReceive(RefArg rcvr);
Ref ZapSend(RefArg rcvr);
Ref ZoomView(RefArg rcvr);

Ref FRecognizeInkWord(RefArg rcvr);
Ref FntpTetheredListener(RefArg rcvr);
Ref FSubstituteChars(RefArg rcvr);
Ref FMatchedChar(RefArg rcvr);
Ref FPathToRoot(RefArg rcvr);
Ref FCircleDistance(RefArg rcvr);
Ref FInTryString(RefArg rcvr);
Ref FGetTrainingData(RefArg rcvr);
Ref FSetLearningData(RefArg rcvr);
Ref FNewByName(RefArg rcvr);
Ref FRecognize(RefArg rcvr);
Ref FGetCardTypes(RefArg rcvr);
Ref FUniqueAppend(RefArg rcvr);
Ref FGetTone(RefArg rcvr);
Ref FLoadOnlinePackage(RefArg rcvr);
Ref FGetZoneList(RefArg rcvr);
Ref FIsMockEntry(RefArg rcvr);
Ref FOtherViewInUse(RefArg rcvr);
Ref FExtractRichStringFromParaSlots(RefArg rcvr);
Ref FPidToPackageLite(RefArg rcvr);
Ref FSetRamParaData(RefArg rcvr);
Ref FComputeParagraphHeight(RefArg rcvr);
Ref FAddHist(RefArg rcvr);
Ref FWRecIsBeingUsed(RefArg rcvr);
Ref FDumpDict(RefArg rcvr);
Ref FHaveZones(RefArg rcvr);
Ref DSTagString(RefArg rcvr);
Ref FPolyContainsInk(RefArg rcvr);
Ref DSFilterStringsAux(RefArg rcvr);
Ref FDSDate(RefArg rcvr);
Ref FGetHiliteIndex(RefArg rcvr);
Ref FGuessAddressee(RefArg rcvr);
Ref FActivateTestAgent(RefArg rcvr);
Ref FFinishRecognizing(RefArg rcvr);
Ref FReadDomainOptions(RefArg rcvr);
Ref FFrameDirty(RefArg rcvr);
Ref FAppleTalkOpenCount(RefArg rcvr);
Ref FDrawStringShapes(RefArg rcvr);
Ref FGetFontFamilyNum(RefArg rcvr);
Ref FUnmountCard(RefArg rcvr);
Ref FTestMDropConnection(RefArg rcvr);
Ref FUnblockStrokes(RefArg rcvr);
Ref FBackLight(RefArg rcvr);
Ref FMakeRegion(RefArg rcvr);
Ref FMergeInk(RefArg rcvr);
Ref FStartIRSniffing(RefArg rcvr);
Ref FStripInk(RefArg rcvr);
Ref FEntryCopy(RefArg rcvr);
Ref FSmartStop(RefArg rcvr);
Ref FGetFontFace(RefArg rcvr);
Ref FCollect(RefArg rcvr);
Ref FSendOnline(RefArg rcvr);
Ref FQuickLookDone(RefArg rcvr);
Ref FTestReadTextFile(RefArg rcvr);
Ref Fmax(RefArg rcvr);
Ref FNextMeeting(RefArg rcvr);
Ref FGetHilitedTextItems(RefArg rcvr);
Ref FReFlow(RefArg rcvr);
Ref FStringAnnotate(RefArg rcvr);
Ref FGetStroke(RefArg rcvr);
Ref FMashLists(RefArg rcvr);
Ref FStringShorten(RefArg rcvr);
Ref DSScanForWackyName(RefArg rcvr);
Ref FGetDictItem(RefArg rcvr);
Ref FGetDefaultFont(RefArg rcvr);
Ref FScanPrevWordEnd(RefArg rcvr);
Ref FStrExactCompare(RefArg rcvr);
Ref FMapSymToFrame(RefArg rcvr);
Ref FPSSidToPkgRef(RefArg rcvr);
Ref FSetFontFamily(RefArg rcvr);
Ref FStringToFrame(RefArg rcvr);
Ref FTestWillCallExit(RefArg rcvr);
Ref FLookupCompletions(RefArg rcvr);
Ref FCompressStrokes(RefArg rcvr);
Ref FInitSerialDebugging(RefArg rcvr);
Ref FRestorePatchPackage(RefArg rcvr);
Ref FGetDictionaryData(RefArg rcvr);
Ref FGetMatchedEntries(RefArg rcvr);
Ref FGetChar(RefArg rcvr);
Ref FGetVBOCompander(RefArg rcvr);
Ref FOpenAppleTalk(RefArg rcvr);
Ref FRemoveAutoAdd(RefArg rcvr);
Ref FSendRemoteControlCode(RefArg rcvr);
Ref FGetInkAt(RefArg rcvr);
Ref FCompositeClass(RefArg rcvr);
Ref FBackupPatchPackage(RefArg rcvr);
Ref FPhoneIndexToValue(RefArg rcvr);
Ref FMakeLexEntry(RefArg rcvr);
Ref FNextInkIndex(RefArg rcvr);
Ref FStdioOn(RefArg rcvr);
Ref FConvertFromMP(RefArg rcvr);
Ref FStrWidth(RefArg rcvr);
Ref FSpellDocBegin(RefArg rcvr);
Ref FFontLeading(RefArg rcvr);
Ref FDisposeTrainingData(RefArg rcvr);
Ref FCloseAppleTalk(RefArg rcvr);
Ref FBackLightStatus(RefArg rcvr);
Ref FBubbleArraySlot(RefArg rcvr);
Ref FAppendList(RefArg rcvr);
Ref FDeActivatePackage(RefArg rcvr);
Ref FTestGetParameterString(RefArg rcvr);
Ref FOpenRemoteControl(RefArg rcvr);
Ref FNewMockEntry(RefArg rcvr);
Ref FSetFontParms(RefArg rcvr);
Ref FSmartCFQuery(RefArg rcvr);
Ref FTestMSetParameterString(RefArg rcvr);
Ref FLookupWord(RefArg rcvr);
Ref FDrawDateLabels(RefArg rcvr);
Ref FScanWordEnd(RefArg rcvr);
Ref FGetViewID(RefArg rcvr);
Ref FCloseRemoteControl(RefArg rcvr);
Ref FRecognizePoly(RefArg rcvr);
Ref FDrawLetterScript(RefArg rcvr);
Ref FGetVBOStoredSize(RefArg rcvr);
Ref FNBPLookupCount(RefArg rcvr);
Ref FStringToNumber(RefArg rcvr);
Ref FGetInsertionStyle(RefArg rcvr);
Ref FParaContainsInk(RefArg rcvr);
Ref FSuffixP(RefArg rcvr);
Ref DSResolveString(RefArg rcvr);
Ref FIsProtocolPartInUse(RefArg rcvr);
Ref FCalcInkBounds(RefArg rcvr);
Ref FMoveCorrectionInfo(RefArg rcvr);
Ref FGetLetterWeights(RefArg rcvr);
Ref FPowerOffRingiSho(RefArg rcvr);
Ref FGetFontSize(RefArg rcvr);
Ref FGetMyZone(RefArg rcvr);
Ref FDeActivate1_2EXPackage(RefArg rcvr);
Ref FRecognizeTextInStyles(RefArg rcvr);
Ref FPhoneSymToString(RefArg rcvr);
Ref FDrawMeetingGrid(RefArg rcvr);
Ref FGetGlobals(RefArg rcvr);
Ref FGetNames(RefArg rcvr);
Ref FlocalVar(RefArg rcvr);
Ref FFontDescent(RefArg rcvr);
Ref FhasSiblingSlot(RefArg rcvr);
Ref FBlockStrokes(RefArg rcvr);
Ref FUnorderedLessOrEqual(RefArg rcvr);
Ref FAddDelayedAction(RefArg rcvr);
Ref FScanWordStart(RefArg rcvr);
Ref FViewAllowsInk(RefArg rcvr);
Ref FStyleArrayContainsInk(RefArg rcvr);
Ref FStrTruncate(RefArg rcvr);
Ref FNBPStartLookup(RefArg rcvr);
Ref FDecodeRichString(RefArg rcvr);
Ref FGetBlue(RefArg rcvr);
Ref FClassInfoRegistrySeed(RefArg rcvr);
Ref FGetExportTableClients(RefArg rcvr);
Ref FIsEqualTone(RefArg rcvr);
Ref FGetCardSlotStores(RefArg rcvr);
Ref FUnionPoint(RefArg rcvr);
Ref FPidToPackage(RefArg rcvr);
Ref Fand(RefArg rcvr);
Ref FFavorObject(RefArg rcvr);
Ref FEntryReplace(RefArg rcvr);
Ref FGetRelevantTemplates(RefArg rcvr);
Ref FEntryReplaceWithModTime(RefArg rcvr);
Ref FLayoutMeeting(RefArg rcvr);
Ref FNBPStart(RefArg rcvr);
Ref FStrFontWidth(RefArg rcvr);
Ref DSPrevSubStr(RefArg rcvr);
Ref FCallOnlineService(RefArg rcvr);
Ref DSFindPossibleLocation(RefArg rcvr);
Ref FMakeInk(RefArg rcvr);
Ref FGetDynamicValue(RefArg rcvr);
Ref FCorrectSelect(RefArg rcvr);
Ref FGetVar(RefArg rcvr);
Ref FMergeStrokes(RefArg rcvr);
Ref DSConstructSubjectLine(RefArg rcvr);
Ref FStrokesAfterUnit(RefArg rcvr);
Ref FTestMStartTestFrame(RefArg rcvr);
Ref FntpDownloadPackage(RefArg rcvr);
Ref FTestReportError(RefArg rcvr);
Ref FSpellDocEnd(RefArg rcvr);
Ref FVBOUndoChanges(RefArg rcvr);
Ref FSetGlobal(RefArg rcvr);
Ref FValidateWord(RefArg rcvr);
Ref FGetLetterHilite(RefArg rcvr);
Ref FAddDeferredAction(RefArg rcvr);
Ref FStripRecognitionWordDiacritsOK(RefArg rcvr);
Ref FTestReportMessage(RefArg rcvr);
Ref FGetVBOCompanderData(RefArg rcvr);
Ref FFastStrLookup(RefArg rcvr);
Ref FRecognizePara(RefArg rcvr);
Ref FGetGreen(RefArg rcvr);
Ref FSetHiliteIndex(RefArg rcvr);
Ref For(RefArg rcvr);
Ref FInkConvert(RefArg rcvr);
Ref FPSSidToPid(RefArg rcvr);
Ref FSplitInkAt(RefArg rcvr);
Ref FNumInkWordsInRange(RefArg rcvr);
Ref FRepeatInfoToText(RefArg rcvr);
Ref FWordUnitToWordInfo(RefArg rcvr);
Ref FStdioOff(RefArg rcvr);
Ref FConnEntriesEqual(RefArg rcvr);
Ref FSpellSkip(RefArg rcvr);
Ref FScanNextWord(RefArg rcvr);
Ref FStringFormat(RefArg rcvr);
Ref FTextBounds(RefArg rcvr);
Ref FScaleShape(RefArg rcvr);
Ref FSetFontFace(RefArg rcvr);
Ref FMakeRichString(RefArg rcvr);
Ref FExpandInk(RefArg rcvr);
Ref FSendAbort(RefArg rcvr);
Ref FReflowPreflight(RefArg rcvr);
Ref FGetVBOStore(RefArg rcvr);
Ref FMapPtY(RefArg rcvr);
Ref FActivatePackage(RefArg rcvr);
Ref FClearTryString(RefArg rcvr);
Ref FFlushStrokes(RefArg rcvr);
Ref FStripRecognitionWord(RefArg rcvr);
Ref FTestReadDataFile(RefArg rcvr);
Ref DSAddLexiconFrame(RefArg rcvr);
Ref FViewWorksWithCombCorrector(RefArg rcvr);
Ref FInsertStyledText(RefArg rcvr);
Ref FGetIndexChar(RefArg rcvr);
Ref FConvertDictionaryData(RefArg rcvr);
Ref FPidToPkgRef(RefArg rcvr);
Ref FSmartConcat(RefArg rcvr);
Ref FAnimateSimpleStroke(RefArg rcvr);
Ref FDSTime(RefArg rcvr);
Ref FGetLetterIndex(RefArg rcvr);
Ref FUnmatchedWords(RefArg rcvr);
Ref FStrokeBundleToInkWord(RefArg rcvr);
Ref FGetLearningData(RefArg rcvr);
Ref FCompressStrokesToInk(RefArg rcvr);
Ref DSFindPossibleName(RefArg rcvr);
Ref DSFindPossiblePhone(RefArg rcvr);
Ref FGetSelectionStack(RefArg rcvr);
Ref FSetDictionaryData(RefArg rcvr);
Ref FDrawOriginal(RefArg rcvr);
Ref FSetChar(RefArg rcvr);
Ref FStopIRSniffing(RefArg rcvr);
Ref FMapCursor(RefArg rcvr);
Ref FConvertForMP(RefArg rcvr);
Ref FPhoneSymToIndex(RefArg rcvr);
Ref FSmartStart(RefArg rcvr);
Ref FTestMStartTestCase(RefArg rcvr);
Ref FGetRamParaData(RefArg rcvr);
Ref FSpellCheck(RefArg rcvr);
Ref FMakePict(RefArg rcvr);
Ref FUseTrainingDataForRecognition(RefArg rcvr);
Ref FMakeStrokeBundle(RefArg rcvr);
Ref FExpandUnit(RefArg rcvr);
Ref FStrCompare(RefArg rcvr);
Ref FGenPhoneTypes(RefArg rcvr);
Ref FTieViews(RefArg rcvr);
Ref FGetFontFamilySym(RefArg rcvr);
Ref FGetStrokePoint(RefArg rcvr);
Ref FEntryMove(RefArg rcvr);
Ref FGetStrokePointsArray(RefArg rcvr);
Ref FFindShape(RefArg rcvr);
Ref FActivate1_2EXPackage(RefArg rcvr);
Ref FCountUnitStrokes(RefArg rcvr);
Ref FMakeRoundRect(RefArg rcvr);
Ref FCoordinateToLongitude(RefArg rcvr);
Ref FLongitudeToCoordinate(RefArg rcvr);
Ref FPictToShape(RefArg rcvr);
Ref FReBoot(RefArg rcvr);
Ref FStringFilter(RefArg rcvr);
Ref FSubsume(RefArg rcvr);
Ref FRosettaExtension(RefArg rcvr);
Ref FCountPoints(RefArg rcvr);
Ref FAddDictionary(RefArg rcvr);
Ref FGetViewFlags(RefArg rcvr);
Ref FGetZoneFromName(RefArg rcvr);
Ref FRemove1_2EXPackage(RefArg rcvr);
Ref FGetRandomDictionaryWord(RefArg rcvr);
Ref FCancelOnlineService(RefArg rcvr);
Ref FMakeWedge(RefArg rcvr);
Ref FPackRGB(RefArg rcvr);
Ref FMakeCompactFont(RefArg rcvr);
Ref FFavorAction(RefArg rcvr);
Ref FNBPGetLookupNames(RefArg rcvr);
Ref FGenSubStrings(RefArg rcvr);
Ref FSetLetterWeights(RefArg rcvr);
Ref FSetFontSize(RefArg rcvr);
Ref FPositionToTime(RefArg rcvr);
Ref FTimeToPosition(RefArg rcvr);
Ref FTestMGetReportMsg(RefArg rcvr);
Ref FDeactivateTestAgent(RefArg rcvr);
Ref FSetTimeHardware(RefArg rcvr);
Ref FFontHeight(RefArg rcvr);
Ref FGenPhrases(RefArg rcvr);
Ref FNBPGetCount(RefArg rcvr);
Ref FResetLetterDefaults(RefArg rcvr);
Ref FClearVBOCache(RefArg rcvr);
Ref FNBPGetNames(RefArg rcvr);
Ref FConnBuildStoreFrame(RefArg rcvr);
Ref FGetRed(RefArg rcvr);
Ref FGetOnlineEndpoint(RefArg rcvr);
Ref FCalcBundleBounds(RefArg rcvr);
Ref FTryStringLength(RefArg rcvr);
Ref FgetSiblingSlot(RefArg rcvr);
Ref FIntersect(RefArg rcvr);
Ref FHist(RefArg rcvr);
Ref FforLoop(RefArg rcvr);
Ref FGetStrokeBounds(RefArg rcvr);
Ref FSetInkerPenSize(RefArg rcvr);
Ref FTestExit(RefArg rcvr);
Ref FRecSettingsChanged(RefArg rcvr);
Ref FGetAllMeetings(RefArg rcvr);
Ref FIsInkChar(RefArg rcvr);
Ref FStripDiacriticals(RefArg rcvr);
Ref FGetEditArray(RefArg rcvr);
Ref FCoordinateToLatitude(RefArg rcvr);
Ref FLatitudeToCoordinate(RefArg rcvr);
Ref FMapRect(RefArg rcvr);
Ref FFontAscent(RefArg rcvr);
Ref FWeekNumber(RefArg rcvr);
Ref FGetMeetingTypeInfo(RefArg rcvr);
Ref FGetNextMeetingTime(RefArg rcvr);
Ref FGetCorrectionWordInfo(RefArg rcvr);
Ref FTestGetParameterArray(RefArg rcvr);
Ref FCorrectWord(RefArg rcvr);
Ref FSetSlot(RefArg rcvr);
Ref FTextBox(RefArg rcvr);
Ref FBuildRecConfig(RefArg rcvr);
Ref FNBPStopLookup(RefArg rcvr);
Ref FGetBitmapInfo(RefArg rcvr);
Ref FMakeOval(RefArg rcvr);
Ref FMungeBitmap(RefArg rcvr);
Ref FSetOnlineDisconnect(RefArg rcvr);
Ref FClickLetterScript(RefArg rcvr);
Ref FGetRangeText(RefArg rcvr);
Ref FSpellCorrect(RefArg rcvr);
Ref FSetPath(RefArg rcvr);
Ref FCommonAncestors(RefArg rcvr);
Ref FSetLetterHilite(RefArg rcvr);
Ref FLower(RefArg rcvr);
Ref FStrAssoc(RefArg rcvr);
Ref FAddAutoAdd(RefArg rcvr);
Ref FCountStrokes(RefArg rcvr);
Ref FAddInk(RefArg rcvr);
Ref FObjectPid(RefArg rcvr);
Ref FGetShapeInfo(RefArg rcvr);
Ref FMungeShape(RefArg rcvr);
Ref FGetDictionary(RefArg rcvr);
Ref Fmin(RefArg rcvr);
Ref FMakePolygon(RefArg rcvr);
Ref FPrevMeeting(RefArg rcvr);
Ref FTriggerWordRecognition(RefArg rcvr);
Ref FMeasuredNumberStr(RefArg rcvr);
Ref FAddTryString(RefArg rcvr);
Ref FNBPStop(RefArg rcvr);
Ref FPhoneStringToValue(RefArg rcvr);
Ref FClassInfoRegistryNext(RefArg rcvr);
Ref FRunInitScripts(RefArg rcvr);
Ref FTestFlushReportQueue(RefArg rcvr);
Ref FAppend(RefArg rcvr);
Ref FDESCreatePasswordKey(RefArg rcvr);
Ref FGetAllMeetingsUnique(RefArg rcvr);
Ref FDSPhone(RefArg rcvr);
Ref FConnectPassthruKeyboard(RefArg rcvr);
Ref FMapPtX(RefArg rcvr);
Ref FCountLetters(RefArg rcvr);
Ref FViewAllowsInkWords(RefArg rcvr);
Ref FPreInitSerialDebugging(RefArg rcvr);
Ref FPointsArrayToStroke(RefArg rcvr);
Ref FClassInfoByName(RefArg rcvr);
Ref FDisconnectOnlineService(RefArg rcvr);
Ref FTranslate(RefArg rcvr);
Ref FDoCursiveTraining(RefArg rcvr);
Ref FPrefixP(RefArg rcvr);
Ref FUseWRec(RefArg rcvr);
Ref FReadCursiveOptions(RefArg rcvr);
Ref DSFilterStrings(RefArg rcvr);
Ref FBootSucceeded(RefArg rcvr);
Ref FGetMeetingIcon(RefArg rcvr);
}

NS_STUB(AddBookmark, RefArg rcvr)
NS_STUB(AddHistory, RefArg rcvr)
NS_STUB(AddInkMarks, RefArg rcvr)
NS_STUB(AddToContentArea, RefArg rcvr)
NS_STUB(Append, RefArg rcvr)
NS_STUB(AuthorData, RefArg rcvr)
NS_STUB(BookClosed, RefArg rcvr)
NS_STUB(BookTitle, RefArg rcvr)
NS_STUB(Bookmarks, RefArg rcvr)
NS_STUB(CFDispose, RefArg rcvr)
NS_STUB(CFInstantiate, RefArg rcvr)
NS_STUB(CFRecord, RefArg rcvr)
NS_STUB(CIAbort, RefArg rcvr)
NS_STUB(CIAccept, RefArg rcvr)
NS_STUB(CIBytesAvailable, RefArg rcvr)
NS_STUB(CICaller, RefArg rcvr)
NS_STUB(CIConnect, RefArg rcvr)
NS_STUB(CIDisconnect, RefArg rcvr)
NS_STUB(CIDispose, RefArg rcvr)
NS_STUB(CIDisposeLeavingTEndpoint, RefArg rcvr)
NS_STUB(CIFlushInput, RefArg rcvr)
NS_STUB(CIFlushOutput, RefArg rcvr)
NS_STUB(CIFlushPartial, RefArg rcvr)
NS_STUB(CIGetOptions, RefArg rcvr)
NS_STUB(CIInput, RefArg rcvr)
NS_STUB(CIInputAvailable, RefArg rcvr)
NS_STUB(CIInstantiate, RefArg rcvr)
NS_STUB(CIInstantiateFromEndpoint, RefArg rcvr)
NS_STUB(CIJustBind, RefArg rcvr)
NS_STUB(CIJustClose, RefArg rcvr)
NS_STUB(CIJustConnect, RefArg rcvr)
NS_STUB(CIJustDisconnect, RefArg rcvr)
NS_STUB(CIJustListen, RefArg rcvr)
NS_STUB(CIJustOpen, RefArg rcvr)
NS_STUB(CIJustRelease, RefArg rcvr)
NS_STUB(CIJustUnBind, RefArg rcvr)
NS_STUB(CIListen, RefArg rcvr)
NS_STUB(CINewAbort, RefArg rcvr)
NS_STUB(CINewAccept, RefArg rcvr)
NS_STUB(CINewBind, RefArg rcvr)
NS_STUB(CINewConnect, RefArg rcvr)
NS_STUB(CINewDisconnect, RefArg rcvr)
NS_STUB(CINewDispose, RefArg rcvr)
NS_STUB(CINewDisposeLeavingTEndpoint, RefArg rcvr)
NS_STUB(CINewDisposeLeavingTool, RefArg rcvr)
NS_STUB(CINewFlushInput, RefArg rcvr)
NS_STUB(CINewFlushPartial, RefArg rcvr)
NS_STUB(CINewInput, RefArg rcvr)
NS_STUB(CINewInstantiate, RefArg rcvr)
NS_STUB(CINewInstantiateFromEndpoint, RefArg rcvr)
NS_STUB(CINewListen, RefArg rcvr)
NS_STUB(CINewOption, RefArg rcvr)
NS_STUB(CINewOutput, RefArg rcvr)
NS_STUB(CINewPartial, RefArg rcvr)
NS_STUB(CINewSetInputSpec, RefArg rcvr)
NS_STUB(CINewSetState, RefArg rcvr)
NS_STUB(CINewState, RefArg rcvr)
NS_STUB(CINewUnBind, RefArg rcvr)
NS_STUB(CIOutput, RefArg rcvr)
NS_STUB(CIOutputDone, RefArg rcvr)
NS_STUB(CIOutputFrame, RefArg rcvr)
NS_STUB(CIPartial, RefArg rcvr)
NS_STUB(CIReadyForOutput, RefArg rcvr)
NS_STUB(CIReject, RefArg rcvr)
NS_STUB(CIRelease, RefArg rcvr)
NS_STUB(CIRequestsPending, RefArg rcvr)
NS_STUB(CISNewInstantiate, RefArg rcvr)
NS_STUB(CISNewInstantiateFromEndpoint, RefArg rcvr)
NS_STUB(CISStreamIn, RefArg rcvr)
NS_STUB(CISStreamOut, RefArg rcvr)
NS_STUB(CISetInputSpec, RefArg rcvr)
NS_STUB(CISetOptions, RefArg rcvr)
NS_STUB(CISetSync, RefArg rcvr)
NS_STUB(CIStartCCL, RefArg rcvr)
NS_STUB(CIState, RefArg rcvr)
NS_STUB(CIStopCCL, RefArg rcvr)
NS_STUB(CSDispose, RefArg rcvr)
NS_STUB(CSGetDefaultConfig, RefArg rcvr)
NS_STUB(CSInstantiate, RefArg rcvr)
NS_STUB(CSSetDefaultConfig, RefArg rcvr)
NS_STUB(CallOnlineServices, RefArg rcvr)
NS_STUB(CheezyIntersect, RefArg rcvr)
NS_STUB(CheezySubsumption, RefArg rcvr)
NS_STUB(CircleDistance, RefArg rcvr)
NS_STUB(CleanString, RefArg rcvr)
NS_STUB(CommonAncestors, RefArg rcvr)
NS_STUB(CompositeClass, RefArg rcvr)
NS_STUB(CoordinateToLatitude, RefArg rcvr)
NS_STUB(CoordinateToLongitude, RefArg rcvr)
NS_STUB(CorrectSelect, RefArg rcvr)
NS_STUB(CorrectWord, RefArg rcvr)
NS_STUB(CountPages, RefArg rcvr)
NS_STUB(CuFind, RefArg rcvr)
NS_STUB(CurrentBook, RefArg rcvr)
NS_STUB(CurrentKiosk, RefArg rcvr)
NS_STUB(CurrentPage, RefArg rcvr)
NS_STUB(DisconnectOnlineServices, RefArg rcvr)
NS_STUB(DumpDict, RefArg rcvr)
NS_STUB(EWBufferStart, RefArg rcvr)
NS_STUB(EWConnectToHost, RefArg rcvr)
NS_STUB(EWDecodePacket, RefArg rcvr)
NS_STUB(EWEscape, RefArg rcvr)
NS_STUB(EWFileToFrame, RefArg rcvr)
NS_STUB(EWFrameToFile, RefArg rcvr)
NS_STUB(EWGetData, RefArg rcvr)
NS_STUB(EWGetError, RefArg rcvr)
NS_STUB(EWGetMacHeader, RefArg rcvr)
NS_STUB(EWInstantiate, RefArg rcvr)
NS_STUB(EWOutput, RefArg rcvr)
NS_STUB(EWOutputAtom, RefArg rcvr)
NS_STUB(EWSend, RefArg rcvr)
NS_STUB(EWSetError, RefArg rcvr)
NS_STUB(EWUnEscape, RefArg rcvr)
NS_STUB(EWUniAtomHandler, RefArg rcvr)
NS_STUB(EWUploadFile, RefArg rcvr)
NS_STUB(FActivate1XPackage, RefArg rcvr)
NS_STUB(FAddCapitalizedEntry, RefArg rcvr)
NS_STUB(FAddUnitInfo, RefArg rcvr)
NS_STUB(FAddWordInfo, RefArg rcvr)
NS_STUB(FAdjustParagraph, RefArg rcvr)
NS_STUB(FAutoAdd, RefArg rcvr)
NS_STUB(FAutoRemove, RefArg rcvr)
NS_STUB(FChildTemplateFromTopic, RefArg rcvr)
NS_STUB(FClearCorrectionInfo, RefArg rcvr)
NS_STUB(FClearWordInfoFlags, RefArg rcvr)
NS_STUB(FClickLetterShapes, RefArg rcvr)
NS_STUB(FCloseRemote, RefArg rcvr)
NS_STUB(FCollapseTopic, RefArg rcvr)
NS_STUB(FConnAbort, RefArg rcvr)
NS_STUB(FConnBytesAvailable, RefArg rcvr)
NS_STUB(FConnConnect, RefArg rcvr)
NS_STUB(FConnDesktopType, RefArg rcvr)
NS_STUB(FConnDoConnection, RefArg rcvr)
NS_STUB(FConnDoKeyboardPassthrough, RefArg rcvr)
NS_STUB(FConnFlushCommandData, RefArg rcvr)
NS_STUB(FConnGetCurrentStore, RefArg rcvr)
NS_STUB(FConnGetSyncChanges, RefArg rcvr)
NS_STUB(FConnInstallProtocolExtension, RefArg rcvr)
NS_STUB(FConnInstantiate, RefArg rcvr)
NS_STUB(FConnReadBytes, RefArg rcvr)
NS_STUB(FConnReadCommand, RefArg rcvr)
NS_STUB(FConnReadCommandData, RefArg rcvr)
NS_STUB(FConnReadCommandHeader, RefArg rcvr)
NS_STUB(FConnRemoveProtocolExtension, RefArg rcvr)
NS_STUB(FConnRetryPassword, RefArg rcvr)
NS_STUB(FConnSetState, RefArg rcvr)
NS_STUB(FConnStop, RefArg rcvr)
NS_STUB(FConnWriteBytes, RefArg rcvr)
NS_STUB(FConnWriteCommand, RefArg rcvr)
NS_STUB(FConnWriteCommandHeader, RefArg rcvr)
NS_STUB(FConnectionState, RefArg rcvr)
NS_STUB(FCountLetterShapes, RefArg rcvr)
NS_STUB(FDeActivate1XPackage, RefArg rcvr)
NS_STUB(FDeleteStoreObject, RefArg rcvr)
NS_STUB(FDestroyProtocol, RefArg rcvr)
NS_STUB(FDispatchProtocol, RefArg rcvr)
NS_STUB(FDoEntryLearning, RefArg rcvr)
NS_STUB(FDrawExpando, RefArg rcvr)
NS_STUB(FDrawLetterShapes, RefArg rcvr)
NS_STUB(FExpandTopic, RefArg rcvr)
NS_STUB(FExtractRange, RefArg rcvr)
NS_STUB(FFindDictionaryFrame, RefArg rcvr)
NS_STUB(FFindNewInfo, RefArg rcvr)
NS_STUB(FFindWordInfo, RefArg rcvr)
NS_STUB(FForLoop, RefArg rcvr)
NS_STUB(FGetBinaryCompander, RefArg rcvr)
NS_STUB(FGetBinaryCompanderData, RefArg rcvr)
NS_STUB(FGetBinaryStore, RefArg rcvr)
NS_STUB(FGetBinaryStoredSize, RefArg rcvr)
NS_STUB(FGetCapability, RefArg rcvr)
NS_STUB(FGetChannelInputGain, RefArg rcvr)
NS_STUB(FGetChannelVolume, RefArg rcvr)
NS_STUB(FGetHiliteWeight, RefArg rcvr)
NS_STUB(FGetSiblingSlot, RefArg rcvr)
NS_STUB(FGetStoreCardSlot, RefArg rcvr)
NS_STUB(FGetStoreCardType, RefArg rcvr)
NS_STUB(FGetStoreObjectSize, RefArg rcvr)
NS_STUB(FGetValue, RefArg rcvr)
NS_STUB(FGetWordInfo, RefArg rcvr)
NS_STUB(FGetWordList, RefArg rcvr)
NS_STUB(FHasCapability, RefArg rcvr)
NS_STUB(FHasSiblingSlot, RefArg rcvr)
NS_STUB(FInsertRange, RefArg rcvr)
NS_STUB(FIsCollapsed, RefArg rcvr)
NS_STUB(FIsLargeBinary, RefArg rcvr)
NS_STUB(FKeyHelpSlipDraw, RefArg rcvr)
NS_STUB(FKeyHelpSlipSetup, RefArg rcvr)
NS_STUB(FKeyboardInputX, RefArg rcvr)
NS_STUB(FLBClearCache, RefArg rcvr)
NS_STUB(FListBottom, RefArg rcvr)
NS_STUB(FLocalVar, RefArg rcvr)
NS_STUB(FMakeDragRef, RefArg rcvr)
NS_STUB(FMakeWordInfo, RefArg rcvr)
NS_STUB(FMarkerBounds, RefArg rcvr)
NS_STUB(FMergeWordInfo, RefArg rcvr)
NS_STUB(FMoveWordFirst, RefArg rcvr)
NS_STUB(FMungeStyles, RefArg rcvr)
NS_STUB(FNewProtocol, RefArg rcvr)
NS_STUB(FNewStoreObject, RefArg rcvr)
NS_STUB(FNextClassInfo, RefArg rcvr)
NS_STUB(FOffsetCorrectionInfo, RefArg rcvr)
NS_STUB(FOpenRemote, RefArg rcvr)
NS_STUB(FPickViewGetScollerValues, RefArg rcvr)
NS_STUB(FPickViewScroll, RefArg rcvr)
NS_STUB(FProcessBuiltinCommand, RefArg rcvr)
NS_STUB(FProtocolImplementationName, RefArg rcvr)
NS_STUB(FProtocolInterfaceName, RefArg rcvr)
NS_STUB(FProtocolSignature, RefArg rcvr)
NS_STUB(FProtocolVersion, RefArg rcvr)
NS_STUB(FReadStoreObject, RefArg rcvr)
NS_STUB(FReboot, RefArg rcvr)
NS_STUB(FRemove1XPackage, RefArg rcvr)
NS_STUB(FRemoveCorrectionInfo, RefArg rcvr)
NS_STUB(FRemoveToggledEntries, RefArg rcvr)
NS_STUB(FResetLearningDefaults, RefArg rcvr)
NS_STUB(FSendCode, RefArg rcvr)
NS_STUB(FSetChannelInputGain, RefArg rcvr)
NS_STUB(FSetChannelVolume, RefArg rcvr)
NS_STUB(FSetHiliteWeight, RefArg rcvr)
NS_STUB(FSetStoreObjectSize, RefArg rcvr)
NS_STUB(FSetWordInfoFlags, RefArg rcvr)
NS_STUB(FSetWordList, RefArg rcvr)
NS_STUB(FSetupTetheredListener, RefArg rcvr)
NS_STUB(FSetupVisibleChildren, RefArg rcvr)
NS_STUB(FSoundClose, RefArg rcvr)
NS_STUB(FSoundIsActive, RefArg rcvr)
NS_STUB(FSoundIsPaused, RefArg rcvr)
NS_STUB(FSoundOpen, RefArg rcvr)
NS_STUB(FSoundPause, RefArg rcvr)
NS_STUB(FSoundSchedule, RefArg rcvr)
NS_STUB(FSoundStart, RefArg rcvr)
NS_STUB(FSoundStop, RefArg rcvr)
NS_STUB(FStoreAbort, RefArg rcvr)
NS_STUB(FStringToFrameMapper, RefArg rcvr)
NS_STUB(FSuckPackageFromBinary, RefArg rcvr)
NS_STUB(FSuckPackageFromEnpoint, RefArg rcvr)
NS_STUB(FSuckPackageOffDeskTop, RefArg rcvr)
NS_STUB(FTXChangeRangeRulers, RefArg rcvr)
NS_STUB(FTXChangeRangeRuns, RefArg rcvr)
NS_STUB(FTXCharToPoint, RefArg rcvr)
NS_STUB(FTXClear, RefArg rcvr)
NS_STUB(FTXCopy, RefArg rcvr)
NS_STUB(FTXCut, RefArg rcvr)
NS_STUB(FTXExternalize, RefArg rcvr)
NS_STUB(FTXFinderFindString, RefArg rcvr)
NS_STUB(FTXFinderGetCountCharacters, RefArg rcvr)
NS_STUB(FTXFinderGetRangeText, RefArg rcvr)
NS_STUB(FTXGetContinuousRun, RefArg rcvr)
NS_STUB(FTXGetCountCharacters, RefArg rcvr)
NS_STUB(FTXGetCountPages, RefArg rcvr)
NS_STUB(FTXGetHiliteRange, RefArg rcvr)
NS_STUB(FTXGetLineRange, RefArg rcvr)
NS_STUB(FTXGetParagraphRange, RefArg rcvr)
NS_STUB(FTXGetRangeData, RefArg rcvr)
NS_STUB(FTXGetScrollValues, RefArg rcvr)
NS_STUB(FTXGetTextViewRect, RefArg rcvr)
NS_STUB(FTXGetTotalHeight, RefArg rcvr)
NS_STUB(FTXGetTotalWidth, RefArg rcvr)
NS_STUB(FTXGetWordRange, RefArg rcvr)
NS_STUB(FTXHideRuler, RefArg rcvr)
NS_STUB(FTXInsertPageBreak, RefArg rcvr)
NS_STUB(FTXInternalize, RefArg rcvr)
NS_STUB(FTXIsModified, RefArg rcvr)
NS_STUB(FTXIsRulerShown, RefArg rcvr)
NS_STUB(FTXPaste, RefArg rcvr)
NS_STUB(FTXPointToChar, RefArg rcvr)
NS_STUB(FTXReplace, RefArg rcvr)
NS_STUB(FTXReplaceAll, RefArg rcvr)
NS_STUB(FTXScroll, RefArg rcvr)
NS_STUB(FTXSetDrawOrigin, RefArg rcvr)
NS_STUB(FTXSetGeometry, RefArg rcvr)
NS_STUB(FTXSetHiliteRange, RefArg rcvr)
NS_STUB(FTXSetReadOnly, RefArg rcvr)
NS_STUB(FTXSetStore, RefArg rcvr)
NS_STUB(FTXShowRuler, RefArg rcvr)
NS_STUB(FTXUpdateRulerInfo, RefArg rcvr)
NS_STUB(FTXViewFindString, RefArg rcvr)
NS_STUB(FTestWordInfoFlags, RefArg rcvr)
NS_STUB(FTopicBottom, RefArg rcvr)
NS_STUB(FTopicIndexToView, RefArg rcvr)
NS_STUB(FVisibleTopicIndex, RefArg rcvr)
NS_STUB(FWriteEntireStoreObject, RefArg rcvr)
NS_STUB(FWriteStoreObject, RefArg rcvr)
NS_STUB(FastStringLookup, RefArg rcvr)
NS_STUB(FavorAction, RefArg rcvr)
NS_STUB(FavorObject, RefArg rcvr)
NS_STUB(Fdim, RefArg rcvr)
NS_STUB(FindContentBySlot, RefArg rcvr)
NS_STUB(FindContentByValue, RefArg rcvr)
NS_STUB(FindPageByContent, RefArg rcvr)
NS_STUB(FindPageBySubject, RefArg rcvr)
NS_STUB(FindPageByValue, RefArg rcvr)
NS_STUB(FormatVertical, RefArg rcvr)
NS_STUB(GenPhoneTypeList, RefArg rcvr)
NS_STUB(GeneratePhrases, RefArg rcvr)
NS_STUB(GenerateSubstrings, RefArg rcvr)
NS_STUB(GetDictItem, RefArg rcvr)
NS_STUB(GetRelevantTemplates, RefArg rcvr)
NS_STUB(GlueStrings, RefArg rcvr)
NS_STUB(GuessAddressee, RefArg rcvr)
NS_STUB(HiliteBlock, RefArg rcvr)
NS_STUB(History, RefArg rcvr)
NS_STUB(IASmartCFLookup, RefArg rcvr)
NS_STUB(ISATest, RefArg rcvr)
NS_STUB(InkMarks, RefArg rcvr)
NS_STUB(LatitudeToCoordinate, RefArg rcvr)
NS_STUB(LayoutMeeting, RefArg rcvr)
NS_STUB(LexDateLookup, RefArg rcvr)
NS_STUB(LexPhoneLookup, RefArg rcvr)
NS_STUB(LexTimeLookup, RefArg rcvr)
NS_STUB(LongitudeToCoordinate, RefArg rcvr)
NS_STUB(MakeLowerCase, RefArg rcvr)
NS_STUB(MakePhrasalLexEntry, RefArg rcvr)
NS_STUB(MapSymToFrame, RefArg rcvr)
NS_STUB(PageContents, RefArg rcvr)
NS_STUB(PageScroll, RefArg rcvr)
NS_STUB(PageThumbnail, RefArg rcvr)
NS_STUB(PathToRoot, RefArg rcvr)
NS_STUB(PhoneIndexToValue, RefArg rcvr)
NS_STUB(PhoneStringToValue, RefArg rcvr)
NS_STUB(PhoneSymToIndex, RefArg rcvr)
NS_STUB(PhoneSymToString, RefArg rcvr)
NS_STUB(PhraseFilter, RefArg rcvr)
NS_STUB(PrefixP, RefArg rcvr)
NS_STUB(PrepBook, RefArg rcvr)
NS_STUB(PrepRecConfig, RefArg rcvr)
NS_STUB(PreviousPage, RefArg rcvr)
NS_STUB(ReFlow, RefArg rcvr)
NS_STUB(ReadDomainOptions, RefArg rcvr)
NS_STUB(ReflowPreflight, RefArg rcvr)
NS_STUB(RefreshTopics, RefArg rcvr)
NS_STUB(RegisterBookRef, RefArg rcvr)
NS_STUB(ScrollToCurrent, RefArg rcvr)
NS_STUB(SendAbort, RefArg rcvr)
NS_STUB(StartIRSniffing, RefArg rcvr)
NS_STUB(StopIRSniffing, RefArg rcvr)
NS_STUB(Store1XPackageToVBO, RefArg rcvr)
NS_STUB(StoreConvertSoupSortTables, RefArg rcvr)
NS_STUB(StorePackageRestore, RefArg rcvr)
NS_STUB(StoreSegmentedPackageRestore, RefArg rcvr)
NS_STUB(SuffixP, RefArg rcvr)
NS_STUB(TableLookup, RefArg rcvr)
NS_STUB(TurnToContent, RefArg rcvr)
NS_STUB(TurnToPage, RefArg rcvr)
NS_STUB(UnionSoupFlush, RefArg rcvr)
NS_STUB(UniqueAppendList, RefArg rcvr)
NS_STUB(UniqueAppendListGen, RefArg rcvr)
NS_STUB(UnmatchedWords, RefArg rcvr)
NS_STUB(UnregisterBookRef, RefArg rcvr)
NS_STUB(UpdateBookmarks, RefArg rcvr)
NS_STUB(UseTrainingDataForRecognition, RefArg rcvr)
NS_STUB(WhereIsBook, RefArg rcvr)
NS_STUB(ZapCancel, RefArg rcvr)
NS_STUB(ZapReceive, RefArg rcvr)
NS_STUB(ZapSend, RefArg rcvr)
NS_STUB(ZoomView, RefArg rcvr)

NS_STUB(FRecognizeInkWord, RefArg rcvr)
NS_STUB(FntpTetheredListener, RefArg rcvr)
NS_STUB(FSubstituteChars, RefArg rcvr)
NS_STUB(FMatchedChar, RefArg rcvr)
NS_STUB(FPathToRoot, RefArg rcvr)
NS_STUB(FCircleDistance, RefArg rcvr)
NS_STUB(FInTryString, RefArg rcvr)
NS_STUB(FGetTrainingData, RefArg rcvr)
NS_STUB(FSetLearningData, RefArg rcvr)
NS_STUB(FNewByName, RefArg rcvr)
NS_STUB(FRecognize, RefArg rcvr)
NS_STUB(FGetCardTypes, RefArg rcvr)
NS_STUB(FUniqueAppend, RefArg rcvr)
NS_STUB(FGetTone, RefArg rcvr)
NS_STUB(FLoadOnlinePackage, RefArg rcvr)
NS_STUB(FGetZoneList, RefArg rcvr)
NS_STUB(FIsMockEntry, RefArg rcvr)
NS_STUB(FOtherViewInUse, RefArg rcvr)
NS_STUB(FExtractRichStringFromParaSlots, RefArg rcvr)
NS_STUB(FPidToPackageLite, RefArg rcvr)
NS_STUB(FSetRamParaData, RefArg rcvr)
NS_STUB(FComputeParagraphHeight, RefArg rcvr)
NS_STUB(FAddHist, RefArg rcvr)
NS_STUB(FWRecIsBeingUsed, RefArg rcvr)
NS_STUB(FDumpDict, RefArg rcvr)
NS_STUB(FHaveZones, RefArg rcvr)
NS_STUB(DSTagString, RefArg rcvr)
NS_STUB(FPolyContainsInk, RefArg rcvr)
NS_STUB(DSFilterStringsAux, RefArg rcvr)
NS_STUB(FDSDate, RefArg rcvr)
NS_STUB(FGetHiliteIndex, RefArg rcvr)
NS_STUB(FGuessAddressee, RefArg rcvr)
NS_STUB(FActivateTestAgent, RefArg rcvr)
NS_STUB(FFinishRecognizing, RefArg rcvr)
NS_STUB(FReadDomainOptions, RefArg rcvr)
NS_STUB(FFrameDirty, RefArg rcvr)
NS_STUB(FAppleTalkOpenCount, RefArg rcvr)
NS_STUB(FDrawStringShapes, RefArg rcvr)
NS_STUB(FGetFontFamilyNum, RefArg rcvr)
NS_STUB(FUnmountCard, RefArg rcvr)
NS_STUB(FTestMDropConnection, RefArg rcvr)
NS_STUB(FUnblockStrokes, RefArg rcvr)
NS_STUB(FBackLight, RefArg rcvr)
NS_STUB(FMakeRegion, RefArg rcvr)
NS_STUB(FMergeInk, RefArg rcvr)
NS_STUB(FStartIRSniffing, RefArg rcvr)
NS_STUB(FStripInk, RefArg rcvr)
NS_STUB(FEntryCopy, RefArg rcvr)
NS_STUB(FSmartStop, RefArg rcvr)
NS_STUB(FGetFontFace, RefArg rcvr)
NS_STUB(FCollect, RefArg rcvr)
NS_STUB(FSendOnline, RefArg rcvr)
NS_STUB(FQuickLookDone, RefArg rcvr)
NS_STUB(FTestReadTextFile, RefArg rcvr)
NS_STUB(Fmax, RefArg rcvr)
NS_STUB(FNextMeeting, RefArg rcvr)
NS_STUB(FGetHilitedTextItems, RefArg rcvr)
NS_STUB(FReFlow, RefArg rcvr)
NS_STUB(FStringAnnotate, RefArg rcvr)
NS_STUB(FGetStroke, RefArg rcvr)
NS_STUB(FMashLists, RefArg rcvr)
NS_STUB(FStringShorten, RefArg rcvr)
NS_STUB(DSScanForWackyName, RefArg rcvr)
NS_STUB(FGetDictItem, RefArg rcvr)
NS_STUB(FGetDefaultFont, RefArg rcvr)
NS_STUB(FScanPrevWordEnd, RefArg rcvr)
NS_STUB(FStrExactCompare, RefArg rcvr)
NS_STUB(FMapSymToFrame, RefArg rcvr)
NS_STUB(FPSSidToPkgRef, RefArg rcvr)
NS_STUB(FSetFontFamily, RefArg rcvr)
NS_STUB(FStringToFrame, RefArg rcvr)
NS_STUB(FTestWillCallExit, RefArg rcvr)
NS_STUB(FLookupCompletions, RefArg rcvr)
NS_STUB(FCompressStrokes, RefArg rcvr)
NS_STUB(FInitSerialDebugging, RefArg rcvr)
NS_STUB(FRestorePatchPackage, RefArg rcvr)
NS_STUB(FGetDictionaryData, RefArg rcvr)
NS_STUB(FGetMatchedEntries, RefArg rcvr)
NS_STUB(FGetChar, RefArg rcvr)
NS_STUB(FGetVBOCompander, RefArg rcvr)
NS_STUB(FOpenAppleTalk, RefArg rcvr)
NS_STUB(FRemoveAutoAdd, RefArg rcvr)
NS_STUB(FSendRemoteControlCode, RefArg rcvr)
NS_STUB(FGetInkAt, RefArg rcvr)
NS_STUB(FCompositeClass, RefArg rcvr)
NS_STUB(FBackupPatchPackage, RefArg rcvr)
NS_STUB(FPhoneIndexToValue, RefArg rcvr)
NS_STUB(FMakeLexEntry, RefArg rcvr)
NS_STUB(FNextInkIndex, RefArg rcvr)
NS_STUB(FStdioOn, RefArg rcvr)
NS_STUB(FConvertFromMP, RefArg rcvr)
NS_STUB(FStrWidth, RefArg rcvr)
NS_STUB(FSpellDocBegin, RefArg rcvr)
NS_STUB(FFontLeading, RefArg rcvr)
NS_STUB(FDisposeTrainingData, RefArg rcvr)
NS_STUB(FCloseAppleTalk, RefArg rcvr)
NS_STUB(FBackLightStatus, RefArg rcvr)
NS_STUB(FBubbleArraySlot, RefArg rcvr)
NS_STUB(FAppendList, RefArg rcvr)
NS_STUB(FDeActivatePackage, RefArg rcvr)
NS_STUB(FTestGetParameterString, RefArg rcvr)
NS_STUB(FOpenRemoteControl, RefArg rcvr)
NS_STUB(FNewMockEntry, RefArg rcvr)
NS_STUB(FSetFontParms, RefArg rcvr)
NS_STUB(FSmartCFQuery, RefArg rcvr)
NS_STUB(FTestMSetParameterString, RefArg rcvr)
NS_STUB(FLookupWord, RefArg rcvr)
NS_STUB(FDrawDateLabels, RefArg rcvr)
NS_STUB(FScanWordEnd, RefArg rcvr)
NS_STUB(FGetViewID, RefArg rcvr)
NS_STUB(FCloseRemoteControl, RefArg rcvr)
NS_STUB(FRecognizePoly, RefArg rcvr)
NS_STUB(FDrawLetterScript, RefArg rcvr)
NS_STUB(FGetVBOStoredSize, RefArg rcvr)
NS_STUB(FNBPLookupCount, RefArg rcvr)
NS_STUB(FStringToNumber, RefArg rcvr)
NS_STUB(FGetInsertionStyle, RefArg rcvr)
NS_STUB(FParaContainsInk, RefArg rcvr)
NS_STUB(FSuffixP, RefArg rcvr)
NS_STUB(DSResolveString, RefArg rcvr)
NS_STUB(FIsProtocolPartInUse, RefArg rcvr)
NS_STUB(FCalcInkBounds, RefArg rcvr)
NS_STUB(FMoveCorrectionInfo, RefArg rcvr)
NS_STUB(FGetLetterWeights, RefArg rcvr)
NS_STUB(FPowerOffRingiSho, RefArg rcvr)
NS_STUB(FGetFontSize, RefArg rcvr)
NS_STUB(FGetMyZone, RefArg rcvr)
NS_STUB(FDeActivate1_2EXPackage, RefArg rcvr)
NS_STUB(FRecognizeTextInStyles, RefArg rcvr)
NS_STUB(FPhoneSymToString, RefArg rcvr)
NS_STUB(FDrawMeetingGrid, RefArg rcvr)
Ref FGetGlobals(RefArg rcvr) { return gVarFrame; }	// as in ROM: the global variables frame
NS_STUB(FGetNames, RefArg rcvr)
NS_STUB(FlocalVar, RefArg rcvr)
NS_STUB(FFontDescent, RefArg rcvr)
NS_STUB(FhasSiblingSlot, RefArg rcvr)
NS_STUB(FBlockStrokes, RefArg rcvr)
NS_STUB(FUnorderedLessOrEqual, RefArg rcvr)
NS_STUB(FAddDelayedAction, RefArg rcvr)
NS_STUB(FScanWordStart, RefArg rcvr)
NS_STUB(FViewAllowsInk, RefArg rcvr)
NS_STUB(FStyleArrayContainsInk, RefArg rcvr)
NS_STUB(FStrTruncate, RefArg rcvr)
NS_STUB(FNBPStartLookup, RefArg rcvr)
NS_STUB(FDecodeRichString, RefArg rcvr)
NS_STUB(FGetBlue, RefArg rcvr)
NS_STUB(FClassInfoRegistrySeed, RefArg rcvr)
NS_STUB(FGetExportTableClients, RefArg rcvr)
NS_STUB(FIsEqualTone, RefArg rcvr)
NS_STUB(FGetCardSlotStores, RefArg rcvr)
NS_STUB(FUnionPoint, RefArg rcvr)
NS_STUB(FPidToPackage, RefArg rcvr)
NS_STUB(Fand, RefArg rcvr)
NS_STUB(FFavorObject, RefArg rcvr)
NS_STUB(FEntryReplace, RefArg rcvr)
NS_STUB(FGetRelevantTemplates, RefArg rcvr)
NS_STUB(FEntryReplaceWithModTime, RefArg rcvr)
NS_STUB(FLayoutMeeting, RefArg rcvr)
NS_STUB(FNBPStart, RefArg rcvr)
NS_STUB(FStrFontWidth, RefArg rcvr)
NS_STUB(DSPrevSubStr, RefArg rcvr)
NS_STUB(FCallOnlineService, RefArg rcvr)
NS_STUB(DSFindPossibleLocation, RefArg rcvr)
NS_STUB(FMakeInk, RefArg rcvr)
NS_STUB(FGetDynamicValue, RefArg rcvr)
NS_STUB(FCorrectSelect, RefArg rcvr)
NS_STUB(FGetVar, RefArg rcvr)
NS_STUB(FMergeStrokes, RefArg rcvr)
NS_STUB(DSConstructSubjectLine, RefArg rcvr)
NS_STUB(FStrokesAfterUnit, RefArg rcvr)
NS_STUB(FTestMStartTestFrame, RefArg rcvr)
NS_STUB(FntpDownloadPackage, RefArg rcvr)
NS_STUB(FTestReportError, RefArg rcvr)
NS_STUB(FSpellDocEnd, RefArg rcvr)
NS_STUB(FVBOUndoChanges, RefArg rcvr)
NS_STUB(FSetGlobal, RefArg rcvr)
NS_STUB(FValidateWord, RefArg rcvr)
NS_STUB(FGetLetterHilite, RefArg rcvr)
NS_STUB(FAddDeferredAction, RefArg rcvr)
NS_STUB(FStripRecognitionWordDiacritsOK, RefArg rcvr)
NS_STUB(FTestReportMessage, RefArg rcvr)
NS_STUB(FGetVBOCompanderData, RefArg rcvr)
NS_STUB(FFastStrLookup, RefArg rcvr)
NS_STUB(FRecognizePara, RefArg rcvr)
NS_STUB(FGetGreen, RefArg rcvr)
NS_STUB(FSetHiliteIndex, RefArg rcvr)
NS_STUB(For, RefArg rcvr)
NS_STUB(FInkConvert, RefArg rcvr)
NS_STUB(FPSSidToPid, RefArg rcvr)
NS_STUB(FSplitInkAt, RefArg rcvr)
NS_STUB(FNumInkWordsInRange, RefArg rcvr)
NS_STUB(FRepeatInfoToText, RefArg rcvr)
NS_STUB(FWordUnitToWordInfo, RefArg rcvr)
NS_STUB(FStdioOff, RefArg rcvr)
NS_STUB(FConnEntriesEqual, RefArg rcvr)
NS_STUB(FSpellSkip, RefArg rcvr)
NS_STUB(FScanNextWord, RefArg rcvr)
NS_STUB(FStringFormat, RefArg rcvr)
NS_STUB(FTextBounds, RefArg rcvr)
NS_STUB(FScaleShape, RefArg rcvr)
NS_STUB(FSetFontFace, RefArg rcvr)
NS_STUB(FMakeRichString, RefArg rcvr)
NS_STUB(FExpandInk, RefArg rcvr)
NS_STUB(FSendAbort, RefArg rcvr)
NS_STUB(FReflowPreflight, RefArg rcvr)
NS_STUB(FGetVBOStore, RefArg rcvr)
NS_STUB(FMapPtY, RefArg rcvr)
NS_STUB(FActivatePackage, RefArg rcvr)
NS_STUB(FClearTryString, RefArg rcvr)
NS_STUB(FFlushStrokes, RefArg rcvr)
NS_STUB(FStripRecognitionWord, RefArg rcvr)
NS_STUB(FTestReadDataFile, RefArg rcvr)
NS_STUB(DSAddLexiconFrame, RefArg rcvr)
NS_STUB(FViewWorksWithCombCorrector, RefArg rcvr)
NS_STUB(FInsertStyledText, RefArg rcvr)
NS_STUB(FGetIndexChar, RefArg rcvr)
NS_STUB(FConvertDictionaryData, RefArg rcvr)
NS_STUB(FPidToPkgRef, RefArg rcvr)
NS_STUB(FSmartConcat, RefArg rcvr)
NS_STUB(FAnimateSimpleStroke, RefArg rcvr)
NS_STUB(FDSTime, RefArg rcvr)
NS_STUB(FGetLetterIndex, RefArg rcvr)
NS_STUB(FUnmatchedWords, RefArg rcvr)
NS_STUB(FStrokeBundleToInkWord, RefArg rcvr)
NS_STUB(FGetLearningData, RefArg rcvr)
NS_STUB(FCompressStrokesToInk, RefArg rcvr)
NS_STUB(DSFindPossibleName, RefArg rcvr)
NS_STUB(DSFindPossiblePhone, RefArg rcvr)
NS_STUB(FGetSelectionStack, RefArg rcvr)
NS_STUB(FSetDictionaryData, RefArg rcvr)
NS_STUB(FDrawOriginal, RefArg rcvr)
NS_STUB(FSetChar, RefArg rcvr)
NS_STUB(FStopIRSniffing, RefArg rcvr)
NS_STUB(FMapCursor, RefArg rcvr)
NS_STUB(FConvertForMP, RefArg rcvr)
NS_STUB(FPhoneSymToIndex, RefArg rcvr)
NS_STUB(FSmartStart, RefArg rcvr)
NS_STUB(FTestMStartTestCase, RefArg rcvr)
NS_STUB(FGetRamParaData, RefArg rcvr)
NS_STUB(FSpellCheck, RefArg rcvr)
NS_STUB(FMakePict, RefArg rcvr)
NS_STUB(FUseTrainingDataForRecognition, RefArg rcvr)
NS_STUB(FMakeStrokeBundle, RefArg rcvr)
NS_STUB(FExpandUnit, RefArg rcvr)
NS_STUB(FStrCompare, RefArg rcvr)
NS_STUB(FGenPhoneTypes, RefArg rcvr)
NS_STUB(FTieViews, RefArg rcvr)
NS_STUB(FGetFontFamilySym, RefArg rcvr)
NS_STUB(FGetStrokePoint, RefArg rcvr)
NS_STUB(FEntryMove, RefArg rcvr)
NS_STUB(FGetStrokePointsArray, RefArg rcvr)
NS_STUB(FFindShape, RefArg rcvr)
NS_STUB(FActivate1_2EXPackage, RefArg rcvr)
NS_STUB(FCountUnitStrokes, RefArg rcvr)
NS_STUB(FMakeRoundRect, RefArg rcvr)
NS_STUB(FCoordinateToLongitude, RefArg rcvr)
NS_STUB(FLongitudeToCoordinate, RefArg rcvr)
NS_STUB(FPictToShape, RefArg rcvr)
NS_STUB(FReBoot, RefArg rcvr)
NS_STUB(FStringFilter, RefArg rcvr)
NS_STUB(FSubsume, RefArg rcvr)
NS_STUB(FRosettaExtension, RefArg rcvr)
NS_STUB(FCountPoints, RefArg rcvr)
NS_STUB(FAddDictionary, RefArg rcvr)
NS_STUB(FGetViewFlags, RefArg rcvr)
NS_STUB(FGetZoneFromName, RefArg rcvr)
NS_STUB(FRemove1_2EXPackage, RefArg rcvr)
NS_STUB(FGetRandomDictionaryWord, RefArg rcvr)
NS_STUB(FCancelOnlineService, RefArg rcvr)
NS_STUB(FMakeWedge, RefArg rcvr)
NS_STUB(FPackRGB, RefArg rcvr)
NS_STUB(FMakeCompactFont, RefArg rcvr)
NS_STUB(FFavorAction, RefArg rcvr)
NS_STUB(FNBPGetLookupNames, RefArg rcvr)
NS_STUB(FGenSubStrings, RefArg rcvr)
NS_STUB(FSetLetterWeights, RefArg rcvr)
NS_STUB(FSetFontSize, RefArg rcvr)
NS_STUB(FPositionToTime, RefArg rcvr)
NS_STUB(FTimeToPosition, RefArg rcvr)
NS_STUB(FTestMGetReportMsg, RefArg rcvr)
NS_STUB(FDeactivateTestAgent, RefArg rcvr)
NS_STUB(FSetTimeHardware, RefArg rcvr)
NS_STUB(FFontHeight, RefArg rcvr)
NS_STUB(FGenPhrases, RefArg rcvr)
NS_STUB(FNBPGetCount, RefArg rcvr)
NS_STUB(FResetLetterDefaults, RefArg rcvr)
NS_STUB(FClearVBOCache, RefArg rcvr)
NS_STUB(FNBPGetNames, RefArg rcvr)
NS_STUB(FConnBuildStoreFrame, RefArg rcvr)
NS_STUB(FGetRed, RefArg rcvr)
NS_STUB(FGetOnlineEndpoint, RefArg rcvr)
NS_STUB(FCalcBundleBounds, RefArg rcvr)
NS_STUB(FTryStringLength, RefArg rcvr)
NS_STUB(FgetSiblingSlot, RefArg rcvr)
NS_STUB(FIntersect, RefArg rcvr)
NS_STUB(FHist, RefArg rcvr)
NS_STUB(FforLoop, RefArg rcvr)
NS_STUB(FGetStrokeBounds, RefArg rcvr)
NS_STUB(FSetInkerPenSize, RefArg rcvr)
NS_STUB(FTestExit, RefArg rcvr)
NS_STUB(FRecSettingsChanged, RefArg rcvr)
NS_STUB(FGetAllMeetings, RefArg rcvr)
NS_STUB(FIsInkChar, RefArg rcvr)
NS_STUB(FStripDiacriticals, RefArg rcvr)
NS_STUB(FGetEditArray, RefArg rcvr)
NS_STUB(FCoordinateToLatitude, RefArg rcvr)
NS_STUB(FLatitudeToCoordinate, RefArg rcvr)
NS_STUB(FMapRect, RefArg rcvr)
NS_STUB(FFontAscent, RefArg rcvr)
NS_STUB(FWeekNumber, RefArg rcvr)
NS_STUB(FGetMeetingTypeInfo, RefArg rcvr)
NS_STUB(FGetNextMeetingTime, RefArg rcvr)
NS_STUB(FGetCorrectionWordInfo, RefArg rcvr)
NS_STUB(FTestGetParameterArray, RefArg rcvr)
NS_STUB(FCorrectWord, RefArg rcvr)
NS_STUB(FSetSlot, RefArg rcvr)
NS_STUB(FTextBox, RefArg rcvr)
NS_STUB(FBuildRecConfig, RefArg rcvr)
NS_STUB(FNBPStopLookup, RefArg rcvr)
NS_STUB(FGetBitmapInfo, RefArg rcvr)
NS_STUB(FMakeOval, RefArg rcvr)
NS_STUB(FMungeBitmap, RefArg rcvr)
NS_STUB(FSetOnlineDisconnect, RefArg rcvr)
NS_STUB(FClickLetterScript, RefArg rcvr)
NS_STUB(FGetRangeText, RefArg rcvr)
NS_STUB(FSpellCorrect, RefArg rcvr)
NS_STUB(FSetPath, RefArg rcvr)
NS_STUB(FCommonAncestors, RefArg rcvr)
NS_STUB(FSetLetterHilite, RefArg rcvr)
NS_STUB(FLower, RefArg rcvr)
NS_STUB(FStrAssoc, RefArg rcvr)
NS_STUB(FAddAutoAdd, RefArg rcvr)
NS_STUB(FCountStrokes, RefArg rcvr)
NS_STUB(FAddInk, RefArg rcvr)
NS_STUB(FObjectPid, RefArg rcvr)
NS_STUB(FGetShapeInfo, RefArg rcvr)
NS_STUB(FMungeShape, RefArg rcvr)
NS_STUB(FGetDictionary, RefArg rcvr)
NS_STUB(Fmin, RefArg rcvr)
NS_STUB(FMakePolygon, RefArg rcvr)
NS_STUB(FPrevMeeting, RefArg rcvr)
NS_STUB(FTriggerWordRecognition, RefArg rcvr)
NS_STUB(FMeasuredNumberStr, RefArg rcvr)
NS_STUB(FAddTryString, RefArg rcvr)
NS_STUB(FNBPStop, RefArg rcvr)
NS_STUB(FPhoneStringToValue, RefArg rcvr)
NS_STUB(FClassInfoRegistryNext, RefArg rcvr)
NS_STUB(FRunInitScripts, RefArg rcvr)
NS_STUB(FTestFlushReportQueue, RefArg rcvr)
NS_STUB(FAppend, RefArg rcvr)
NS_STUB(FDESCreatePasswordKey, RefArg rcvr)
NS_STUB(FGetAllMeetingsUnique, RefArg rcvr)
NS_STUB(FDSPhone, RefArg rcvr)
NS_STUB(FConnectPassthruKeyboard, RefArg rcvr)
NS_STUB(FMapPtX, RefArg rcvr)
NS_STUB(FCountLetters, RefArg rcvr)
NS_STUB(FViewAllowsInkWords, RefArg rcvr)
NS_STUB(FPreInitSerialDebugging, RefArg rcvr)
NS_STUB(FPointsArrayToStroke, RefArg rcvr)
NS_STUB(FClassInfoByName, RefArg rcvr)
NS_STUB(FDisconnectOnlineService, RefArg rcvr)
NS_STUB(FTranslate, RefArg rcvr)
NS_STUB(FDoCursiveTraining, RefArg rcvr)
NS_STUB(FPrefixP, RefArg rcvr)
NS_STUB(FUseWRec, RefArg rcvr)
NS_STUB(FReadCursiveOptions, RefArg rcvr)
NS_STUB(DSFilterStrings, RefArg rcvr)
NS_STUB(FBootSucceeded, RefArg rcvr)
NS_STUB(FGetMeetingIcon, RefArg rcvr)
