#!/bin/bash

./build/VSCode/newtc -pkg "$1" -decompile >/tmp/newtc_a
./build/VSCode/newtc -pkg "$1" -debug bc -decompile >/tmp/newtc_b
./build/VSCode/newtc -script /tmp/newtc_a -debug bc -decompile >/tmp/newtc_c
#diff -b -B -i /tmp/newtc_b /tmp/newtc_c

