#!/usr/bin/env python3
"""The ROM as assembler source, verbatim (R2).

    romasm.py <rom-dir> <out-dir> [--chunk BYTES]

From romsyms.py's output (ro.bin, rw.bin, symbols.json), writes ARM6asm
source that ARMLink turns back into Apple's image:

    ro_NN.a      the read-only part in pieces of about --chunk bytes (cut at
                 a symbol), one area each (|ROM$$RO$$NN|: the linker sorts
                 areas by name, so the pieces stay in order)
    rw.a         the read-write data (|ROM$$RW|, linked to run at its base)
    zi.a         the zero-initialised data (|ROM$$ZI|, NOINIT), after it
    scatter.txt  the scatter file, as Apple's link had it: the root region
                 at 0, its data at the RW base (so the linker makes Apple's
                 symbols: ROM$$Size, Image$$root$$Base, Load$$root$$Base, ...)
    files.txt    the files in link order
    link.txt     the linker's options

Every symbol becomes a label. A name the ROM has once is exported, so C++
can call it; a name it has more than once (local functions of different
files) gets its address appended (|Name@0x1234|) and stays local. The
linker's own symbols ($$ in the name) are left out: the linker makes them.
Words go out as DCD (only at word-aligned addresses), other bytes as DCB.
"""

import argparse
import json
import os
import struct
import sys
from collections import defaultdict


def label_names(symbols, low, high):
    """Labels for the symbols in [low, high): address -> [(label, exported)]."""
    count = defaultdict(int)
    for s in symbols:
        count[s['name']] += 1
    at = defaultdict(list)
    for s in symbols:
        name, value = s['name'], s['value']
        if not (low <= value < high) or '$$' in name:
            continue
        if count[name] == 1:
            at[value].append((name, True))
        else:
            at[value].append(('%s@0x%X' % (name, value), False))
    return at


def emit_bytes(out, data, start, end, origin):
    """data[start-origin:end-origin] as DCB/DCD lines; start, end: addresses."""
    a = start
    while a < end and a % 4:
        n = min(end, (a + 4) & ~3) - a
        out.append('        DCB ' + ','.join('&%02X' % b for b in data[a - origin:a - origin + n]))
        a += n
    words = (end - a) // 4
    for i in range(0, words, 8):
        k = min(8, words - i)
        ws = struct.unpack_from('>%dI' % k, data, a - origin + 4 * i)
        out.append('        DCD ' + ','.join('&%08X' % w for w in ws))
    a += words * 4
    if a < end:
        out.append('        DCB ' + ','.join('&%02X' % b for b in data[a - origin:end - origin]))


def write_zi(path, area, labels, start, end):
    out = ['; generated by tools/romasm.py from Apple\'s ROM image: do not edit',
           '        AREA |%s|, NOINIT' % area]
    for a in sorted(labels):
        for n, e in labels[a]:
            if e:
                out.append('        EXPORT |%s|' % n)
    a = start
    for p in sorted(labels):
        if p > a:
            out.append('        %% %d' % (p - a))
        for n, _ in labels[p]:
            out.append('|%s|' % n)
        a = p
    if end > a:
        out.append('        %% %d' % (end - a))
    out += ['        END', '']
    with open(path, 'w') as f:
        f.write('\n'.join(out))


def write_area(path, area, attrs, data, origin, labels, start, end):
    out = ['; generated by tools/romasm.py from Apple\'s ROM image: do not edit',
           '        AREA |%s|, %s' % (area, attrs)]
    exports = [n for a in sorted(labels) if start <= a < end for n, e in labels[a] if e]
    for n in exports:
        out.append('        EXPORT |%s|' % n)
    points = sorted(a for a in labels if start <= a < end)
    a = start
    for p in points:
        emit_bytes(out, data, a, p, origin)
        for n, _ in labels[p]:
            out.append('|%s|' % n)
        a = p
    emit_bytes(out, data, a, end, origin)
    out += ['        END', '']
    with open(path, 'w') as f:
        f.write('\n'.join(out))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('rom')
    ap.add_argument('out')
    ap.add_argument('--chunk', type=int, default=0x40000)
    args = ap.parse_args()
    with open(os.path.join(args.rom, 'ro.bin'), 'rb') as f:
        ro = f.read()
    with open(os.path.join(args.rom, 'rw.bin'), 'rb') as f:
        rw = f.read()
    with open(os.path.join(args.rom, 'symbols.json')) as f:
        info = json.load(f)
    symbols = info['symbols']
    rw_base = info['image']['rw_base']
    os.makedirs(args.out, exist_ok=True)

    ro_labels = label_names(symbols, 0, len(ro))
    starts = sorted(a for a in ro_labels if a % 4 == 0)
    cuts = [0]
    target = args.chunk
    for a in starts:
        if a >= target:
            cuts.append(a)
            target = a + args.chunk
    cuts.append(len(ro))
    files = []
    for i in range(len(cuts) - 1):
        name = 'ro_%02d.a' % i
        write_area(os.path.join(args.out, name), 'ROM$$RO$$%02d' % i, 'CODE, READONLY',
                   ro, 0, ro_labels, cuts[i], cuts[i + 1])
        files.append(name)
    rw_labels = label_names(symbols, rw_base, rw_base + len(rw))
    write_area(os.path.join(args.out, 'rw.a'), 'ROM$$RW', 'DATA',
               rw, rw_base, rw_labels, rw_base, rw_base + len(rw))
    files.append('rw.a')
    zi_base = rw_base + len(rw)
    zi_size = info['image']['zi_size']
    zi_labels = label_names(symbols, zi_base, zi_base + zi_size)
    write_zi(os.path.join(args.out, 'zi.a'), 'ROM$$ZI', zi_labels, zi_base, zi_base + zi_size)
    files.append('zi.a')
    with open(os.path.join(args.out, 'scatter.txt'), 'w') as f:
        f.write('ROOT 0x%X\nROOT-DATA 0x%X\n' % (info['image']['ro_base'], rw_base))
    with open(os.path.join(args.out, 'files.txt'), 'w') as f:
        f.write('\n'.join(files) + '\n')
    with open(os.path.join(args.out, 'link.txt'), 'w') as f:
        f.write('-AIF -NOZEROpad -Entry 0x%X -SCATTER scatter.txt\n' % info['image']['ro_base'])
    nlabels = sum(len(v) for d in (ro_labels, rw_labels, zi_labels) for v in d.values())
    print('%d files, %d labels (RO 0x%X bytes, RW 0x%X bytes)' % (len(files), nlabels, len(ro), len(rw)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
