#!/usr/bin/env python3
"""Declarations of the ROM's NewtonScript constants for C++ (R6).

    rsheaders.py <romsyms output> <src dir>

After the object area come the R and RS constants (romasm.py's R3f): an R
word holds a Ref to an object in ROM, an RS word the address of an R word.
Code passes an RS word's address as a RefArg (a RefVar holds a pointer to a
handle whose first word is the Ref: the R word serves as one). Writes, from
Apple's symbol table:

    Frames/RSSymbols.h     extern Ref * RSSYMname; for every symbol
    Frames/ROMResources.h  extern Ref * RSname; for every other object,
                           and RA(name), SYMA(name): the constant as a RefArg
"""

import json
import os
import sys

HEAD = '''/*
	File:		%s

	Contains:	%s

	Generated by tools/rsheaders.py from Apple's symbol table: do not edit.
*/

#ifndef %s
#define %s

'''


def write(path, guard, contents, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(HEAD % (os.path.basename(path), contents, guard, guard))
        f.write('\n'.join(lines) + '\n\n#endif\t/* %s */\n' % guard)


def main():
    rom, src = sys.argv[1:3]
    with open(os.path.join(rom, 'symbols.json')) as f:
        info = json.load(f)
    names = {s['name']: s['value'] for s in info['symbols']}
    low, high = names['gROMSoupDataSize'], names['gROMSoupDataSize'] + 0x6000
    rs = sorted({s['name'] for s in info['symbols']
                 if s['name'].startswith('RS') and low < s['value'] < high})
    symbols = [n for n in rs if n.startswith('RSSYM')]
    others = [n for n in rs if not n.startswith('RSSYM')]
    write(os.path.join(src, 'Frames', 'ROMResources.h'), '__ROMRESOURCES_H',
          "The ROM's NewtonScript objects (RS constants), and RA, SYMA.",
          ['#include "Frames/objects.h"', '',
           '/* a ROM constant as a RefArg: RA(canonicalrect), SYMA(name) (lower case, as in the ROM) */',
           '#define RA(name)\t(*(RefVar *) &RS##name)',
           '#define SYMA(name)\tRA(SYM##name)', '']
          + ['extern Ref *\t%s;' % n for n in others])
    write(os.path.join(src, 'Frames', 'RSSymbols.h'), '__RSSYMBOLS_H',
          "The ROM's NewtonScript symbols (RS constants).",
          ['#ifndef __ROMRESOURCES_H', '#include "Frames/ROMResources.h"', '#endif', '']
          + ['extern Ref *\t%s;' % n for n in symbols])
    print('%d symbols, %d other objects' % (len(symbols), len(others)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
